//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace TestContracts;
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_LegacyRequest_Formatter : IonFormatter<LegacyRequest>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public LegacyRequest Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __oldid = IonFormatterStorage<i4>.Read(reader);
        var __name = IonFormatterStorage<string>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__oldid, __name);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, LegacyRequest value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<i4>.Write(writer, value.oldId);
        IonFormatterStorage<string>.Write(writer, value.name);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_CacheProbe_Formatter : IonFormatter<CacheProbe>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public CacheProbe Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __hits = IonFormatterStorage<i4>.Read(reader);
        var __misses = IonFormatterStorage<i4>.Read(reader);
        var __total = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 3);
        return new(__hits, __misses, __total);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, CacheProbe value)
    {
        writer.WriteStartArray(3);
        IonFormatterStorage<i4>.Write(writer, value.hits);
        IonFormatterStorage<i4>.Write(writer, value.misses);
        IonFormatterStorage<i4>.Write(writer, value.total);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_CacheRegion_Formatter : IonFormatter<CacheRegion>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public CacheRegion Read(CborReader reader)
    {
         return (CacheRegion)(IonFormatterStorage<i4>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, CacheRegion value)
    {
        var casted = (i4)value;
        IonFormatterStorage<i4>.Write(writer, casted);
    }
}

