//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace TestContracts;
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_Member_Formatter : IonFormatter<Member>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public Member Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __id = IonFormatterStorage<guid>.Read(reader);
        var __name = IonFormatterStorage<string>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__id, __name);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, Member value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<guid>.Write(writer, value.id);
        IonFormatterStorage<string>.Write(writer, value.name);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_Doc_Formatter : IonFormatter<Doc>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public Doc Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __title = IonFormatterStorage<string>.Read(reader);
        var __revision = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__title, __revision);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, Doc value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<string>.Write(writer, value.title);
        IonFormatterStorage<i4>.Write(writer, value.revision);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_KeyMatrix_Formatter : IonFormatter<KeyMatrix>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public KeyMatrix Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __byi1 = IonFormatterStorage<Dictionary<i1, i4>>.Read(reader);
        var __byi2 = IonFormatterStorage<Dictionary<i2, i4>>.Read(reader);
        var __byi4 = IonFormatterStorage<Dictionary<i4, i4>>.Read(reader);
        var __byi8 = IonFormatterStorage<Dictionary<i8, i4>>.Read(reader);
        var __byi16 = IonFormatterStorage<Dictionary<i16, i4>>.Read(reader);
        var __byu1 = IonFormatterStorage<Dictionary<u1, i4>>.Read(reader);
        var __byu2 = IonFormatterStorage<Dictionary<u2, i4>>.Read(reader);
        var __byu4 = IonFormatterStorage<Dictionary<u4, i4>>.Read(reader);
        var __byu8 = IonFormatterStorage<Dictionary<u8, i4>>.Read(reader);
        var __byu16 = IonFormatterStorage<Dictionary<u16, i4>>.Read(reader);
        var __bybool = IonFormatterStorage<Dictionary<bool, i4>>.Read(reader);
        var __bystring = IonFormatterStorage<Dictionary<string, i4>>.Read(reader);
        var __byguid = IonFormatterStorage<Dictionary<guid, i4>>.Read(reader);
        var __byenum = IonFormatterStorage<Dictionary<Tier, i4>>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 14);
        return new(__byi1, __byi2, __byi4, __byi8, __byi16, __byu1, __byu2, __byu4, __byu8, __byu16, __bybool, __bystring, __byguid, __byenum);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, KeyMatrix value)
    {
        writer.WriteStartArray(14);
        IonFormatterStorage<Dictionary<i1, i4>>.Write(writer, value.byI1);
        IonFormatterStorage<Dictionary<i2, i4>>.Write(writer, value.byI2);
        IonFormatterStorage<Dictionary<i4, i4>>.Write(writer, value.byI4);
        IonFormatterStorage<Dictionary<i8, i4>>.Write(writer, value.byI8);
        IonFormatterStorage<Dictionary<i16, i4>>.Write(writer, value.byI16);
        IonFormatterStorage<Dictionary<u1, i4>>.Write(writer, value.byU1);
        IonFormatterStorage<Dictionary<u2, i4>>.Write(writer, value.byU2);
        IonFormatterStorage<Dictionary<u4, i4>>.Write(writer, value.byU4);
        IonFormatterStorage<Dictionary<u8, i4>>.Write(writer, value.byU8);
        IonFormatterStorage<Dictionary<u16, i4>>.Write(writer, value.byU16);
        IonFormatterStorage<Dictionary<bool, i4>>.Write(writer, value.byBool);
        IonFormatterStorage<Dictionary<string, i4>>.Write(writer, value.byString);
        IonFormatterStorage<Dictionary<guid, i4>>.Write(writer, value.byGuid);
        IonFormatterStorage<Dictionary<Tier, i4>>.Write(writer, value.byEnum);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_ContainerShapes_Formatter : IonFormatter<ContainerShapes>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public ContainerShapes Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __tags = IonFormatterStorage<Dictionary<string, i4>>.Read(reader);
        var __ids = IonFormatterStorage<HashSet<i4>>.Read(reader);
        var __coords = IonFormatterStorage<f4>.ReadFixedArray(reader, 16);
        var __membersbyname = reader.ReadNullable<Dictionary<string, Member>>();
        var __groups = IonFormatterStorage<HashSet<i4>>.ReadArray(reader);
        var __layers = IonFormatterStorage<HashSet<i4>>.ReadArray(reader);
        var __offsets = IonFormatterStorage<f4>.ReadNullableFixedArray(reader, 16);
        var __patches = IonFormatterStorage<Dictionary<string, IonPartial<Doc>>>.Read(reader);
        var __rosters = IonFormatterStorage<Dictionary<string, IonArray<Member>>>.Read(reader);
        var __cohorts = IonFormatterStorage<Dictionary<Tier, HashSet<i4>>>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 10);
        return new(__tags, __ids, __coords, __membersbyname, __groups, __layers, __offsets, __patches, __rosters, __cohorts);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, ContainerShapes value)
    {
        writer.WriteStartArray(10);
        IonFormatterStorage<Dictionary<string, i4>>.Write(writer, value.tags);
        IonFormatterStorage<HashSet<i4>>.Write(writer, value.ids);
        IonFormatterStorage<f4>.WriteFixedArray(writer, value.coords, 16);
        IonFormatterStorage<Dictionary<string, Member>>.WriteNullable(writer, value.membersByName);
        IonFormatterStorage<HashSet<i4>>.WriteArray(writer, value.groups);
        IonFormatterStorage<HashSet<i4>>.WriteArray(writer, value.layers);
        IonFormatterStorage<f4>.WriteNullableFixedArray(writer, value.offsets, 16);
        IonFormatterStorage<Dictionary<string, IonPartial<Doc>>>.Write(writer, value.patches);
        IonFormatterStorage<Dictionary<string, IonArray<Member>>>.Write(writer, value.rosters);
        IonFormatterStorage<Dictionary<Tier, HashSet<i4>>>.Write(writer, value.cohorts);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_Tier_Formatter : IonFormatter<Tier>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public Tier Read(CborReader reader)
    {
         return (Tier)(IonFormatterStorage<u1>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, Tier value)
    {
        var casted = (u1)value;
        IonFormatterStorage<u1>.Write(writer, casted);
    }
}

