//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace TestContracts;
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_LedgerEntry_Formatter : IonFormatter<LedgerEntry>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public LedgerEntry Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __bookedat = IonFormatterStorage<datetime>.Read(reader);
        var __amount = IonFormatterStorage<decimal>.Read(reader);
        var __settledat = reader.ReadNullable<datetime>();
        var __fee = reader.ReadNullable<decimal>();
        var __revisions = IonFormatterStorage<datetime>.ReadArray(reader);
        var __adjustments = IonFormatterStorage<decimal>.ReadArray(reader);
        var __corrections = IonFormatterStorage<decimal>.ReadNullableArray(reader);
        var __openedat = IonFormatterStorage<datetime>.Read(reader);
        var __openingbalance = IonFormatterStorage<decimal>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 9);
        return new(__bookedat, __amount, __settledat, __fee, __revisions, __adjustments, __corrections, __openedat, __openingbalance);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, LedgerEntry value)
    {
        writer.WriteStartArray(9);
        IonFormatterStorage<datetime>.Write(writer, value.bookedAt);
        IonFormatterStorage<decimal>.Write(writer, value.amount);
        IonFormatterStorage<datetime>.WriteNullable(writer, value.settledAt);
        IonFormatterStorage<decimal>.WriteNullable(writer, value.fee);
        IonFormatterStorage<datetime>.WriteArray(writer, value.revisions);
        IonFormatterStorage<decimal>.WriteArray(writer, value.adjustments);
        IonFormatterStorage<decimal>.WriteNullableArray(writer, value.corrections);
        IonFormatterStorage<datetime>.Write(writer, value.openedAt);
        IonFormatterStorage<decimal>.Write(writer, value.openingBalance);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_LedgerPatch_Formatter : IonFormatter<LedgerPatch>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public LedgerPatch Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __bookedat = IonFormatterStorage<datetime>.Read(reader);
        var __amount = IonFormatterStorage<decimal>.Read(reader);
        var __settledat = reader.ReadNullable<datetime>();
        var __adjustments = IonFormatterStorage<decimal>.ReadArray(reader);
        reader.ReadEndArrayAndSkip(arraySize - 4);
        return new(__bookedat, __amount, __settledat, __adjustments);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, LedgerPatch value)
    {
        writer.WriteStartArray(4);
        IonFormatterStorage<datetime>.Write(writer, value.bookedAt);
        IonFormatterStorage<decimal>.Write(writer, value.amount);
        IonFormatterStorage<datetime>.WriteNullable(writer, value.settledAt);
        IonFormatterStorage<decimal>.WriteArray(writer, value.adjustments);
        writer.WriteEndArray();
    }
}

