//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace TestContracts;
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
internal static class IonProjectFormatterStorageModuleInit
{
    [ModuleInitializer]
    internal static void Init()
    {
        
      IonFormatterStorage<Vector>.Value = new Ion_Vector_Formatter();
      IonFormatterStorage<VectorOfVector>.Value = new Ion_VectorOfVector_Formatter();
      IonFormatterStorage<VectorOfVectorOfVector>.Value = new Ion_VectorOfVectorOfVector_Formatter();
      IonExecutorMetadataStorage.AddExecutor<Ion_MathInteraction_ServiceExecutor>("IMathInteraction");
      IonExecutorMetadataStorage.AddExecutor<Ion_RandomStreamInteraction_ServiceExecutor>("IRandomStreamInteraction");
      IonExecutorMetadataStorage.AddExecutor<Ion_VectorMathInteraction_ServiceExecutor>("IVectorMathInteraction");
      IonExecutorMetadataStorage.AddClient<Ion_MathInteraction_ClientImpl>("IMathInteraction");
      IonExecutorMetadataStorage.AddClient<Ion_RandomStreamInteraction_ClientImpl>("IRandomStreamInteraction");
      IonExecutorMetadataStorage.AddClient<Ion_VectorMathInteraction_ClientImpl>("IVectorMathInteraction");

    }
}
