//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace TestContracts;
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_PatchTarget_Formatter : IonFormatter<PatchTarget>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public PatchTarget Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __n = IonFormatterStorage<i4>.Read(reader);
        var __f = IonFormatterStorage<f4>.Read(reader);
        var __s = IonFormatterStorage<string>.Read(reader);
        var __items = IonFormatterStorage<i4>.ReadArray(reader);
        var __note = reader.ReadNullable<string>();
        reader.ReadEndArrayAndSkip(arraySize - 5);
        return new(__n, __f, __s, __items, __note);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, PatchTarget value)
    {
        writer.WriteStartArray(5);
        IonFormatterStorage<i4>.Write(writer, value.n);
        IonFormatterStorage<f4>.Write(writer, value.f);
        IonFormatterStorage<string>.Write(writer, value.s);
        IonFormatterStorage<i4>.WriteArray(writer, value.items);
        IonFormatterStorage<string>.WriteNullable(writer, value.note);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_PatchEnvelope_Formatter : IonFormatter<PatchEnvelope>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public PatchEnvelope Read(CborReader reader)
    {
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");;
        var __one = IonFormatterStorage<IonPartial<PatchTarget>>.Read(reader);
        var __many = IonFormatterStorage<IonPartial<PatchTarget>>.ReadArray(reader);
        var __maybe = reader.ReadNullable<IonPartial<PatchTarget>>();
        var __maybemany = IonFormatterStorage<IonPartial<PatchTarget>>.ReadNullableArray(reader);
        reader.ReadEndArrayAndSkip(arraySize - 4);
        return new(__one, __many, __maybe, __maybemany);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, PatchEnvelope value)
    {
        writer.WriteStartArray(4);
        IonFormatterStorage<IonPartial<PatchTarget>>.Write(writer, value.one);
        IonFormatterStorage<IonPartial<PatchTarget>>.WriteArray(writer, value.many);
        IonFormatterStorage<IonPartial<PatchTarget>>.WriteNullable(writer, value.maybe);
        IonFormatterStorage<IonPartial<PatchTarget>>.WriteNullableArray(writer, value.maybeMany);
        writer.WriteEndArray();
    }
}

