//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace TestContracts;
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_Vector_Formatter : IonFormatter<Vector>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public Vector Read(CborReader reader)
    {
        var __x = IonFormatterStorage<f4>.Read(reader);
        var __y = IonFormatterStorage<f4>.Read(reader);
        var __z = IonFormatterStorage<f4>.Read(reader);
        return new(__x, __y, __z);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, Vector value)
    {
        IonFormatterStorage<f4>.Write(writer, value.x);
        IonFormatterStorage<f4>.Write(writer, value.y);
        IonFormatterStorage<f4>.Write(writer, value.z);
    }
}

