//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace TestContracts;

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record Vector(f4 x, f4 y, f4 z);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record VectorOfVector(Vector x, Vector y, Vector z);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record VectorOfVectorOfVector(VectorOfVector z, VectorOfVector w);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface IVectorMathInteraction : IIonService
{
    Task<Vector> Abs(Vector leftOperand, CancellationToken ct = default);
    Task<Vector> Add(Vector leftOperand, Vector rightOperand, CancellationToken ct = default);
    Task<Vector> AndNot(Vector leftOperand, Vector rightOperand, CancellationToken ct = default);
    Task<Vector> Clamp(Vector leftOperand, Vector min, Vector max, CancellationToken ct = default);
    Task<VectorOfVectorOfVector> Do(Vector leftOperand, CancellationToken ct = default);
}


