//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------
#![allow(dead_code, unused_imports, non_camel_case_types)]
//! Binary payload round-trip contracts.
//!
//! These services exist to exercise the `bytes` primitive across every method
//! shape the runtime supports: void return, single round-trip, and repeated
//! round-trips over the same connection.
//!
//! Arithmetic RPC surface used by the IonPath integration tests.
//!
//! Every service in this module is stateless: the left-hand operand is bound
//! once, as a service argument, and reused by every method call on that client.

use ion_rustcore::formatter::IonFormat;
use ion_rustcore::{Decoder, Encoder, IonError};
pub use futures_util::StreamExt;

// ═══════════════ Types ═══════════════

#[derive(Debug, Clone, PartialEq)]
pub struct Vector {
    pub x: f32,
    pub y: f32,
    pub z: f32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct VectorOfVector {
    pub x: Vector,
    pub y: Vector,
    pub z: Vector,
}


#[derive(Debug, Clone, PartialEq)]
pub struct VectorOfVectorOfVector {
    pub z: VectorOfVector,
    pub w: VectorOfVector,
}



// ═══════════════ Formatters ═══════════════

impl IonFormat for Vector {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let len = d.array()?.ok_or(IonError::IndefiniteArray)?;
        let x = <f32 as IonFormat>::ion_read(d)?;
        let y = <f32 as IonFormat>::ion_read(d)?;
        let z = <f32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 3)?;
        Ok(Self { x, y, z })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(3)?;
        self.x.ion_write(e)?;
        self.y.ion_write(e)?;
        self.z.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for VectorOfVector {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let len = d.array()?.ok_or(IonError::IndefiniteArray)?;
        let x = <Vector as IonFormat>::ion_read(d)?;
        let y = <Vector as IonFormat>::ion_read(d)?;
        let z = <Vector as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 3)?;
        Ok(Self { x, y, z })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(3)?;
        self.x.ion_write(e)?;
        self.y.ion_write(e)?;
        self.z.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for VectorOfVectorOfVector {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let len = d.array()?.ok_or(IonError::IndefiniteArray)?;
        let z = <VectorOfVector as IonFormat>::ion_read(d)?;
        let w = <VectorOfVector as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { z, w })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.z.ion_write(e)?;
        self.w.ion_write(e)?;
        Ok(())
    }
}


// ═══════════════ Service Clients ═══════════════

/// Blob echo service used by the transport tests.
///
/// Nothing here interprets the payload; the methods only prove that a byte
/// buffer survives serialization, transport and deserialization unchanged.
pub struct TestBlobsClient {
    ctx: ion_rustcore::IonClientContext,
}

impl ion_rustcore::FromContext for TestBlobsClient {
    fn from_context(ctx: ion_rustcore::IonClientContext) -> Self {
        Self { ctx }
    }
}

impl TestBlobsClient {
        /// Accepts a payload and returns nothing. Exercises the void-return path.
    pub async fn r#do(&self, data: &ion_rustcore::IonBytes) -> Result<(), ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(1)?;
        data.ion_write(&mut e)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "ITestBlobs", "Do");
        req.call_void(&buf).await
    }
    /// Echoes the payload back to the caller.
    pub async fn do_it(&self, data: &ion_rustcore::IonBytes) -> Result<ion_rustcore::IonBytes, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(1)?;
        data.ion_write(&mut e)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "ITestBlobs", "DoIt");
        req.call::<ion_rustcore::IonBytes>(&buf).await
    }
    /// Second echo overload. The duplicate methods let the tests issue several
    /// distinct calls over one connection without reusing a method name.
    pub async fn do_it2(&self, data: &ion_rustcore::IonBytes) -> Result<ion_rustcore::IonBytes, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(1)?;
        data.ion_write(&mut e)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "ITestBlobs", "DoIt2");
        req.call::<ion_rustcore::IonBytes>(&buf).await
    }
    /// Third echo overload. See DoIt2.
    pub async fn do_it3(&self, data: &ion_rustcore::IonBytes) -> Result<ion_rustcore::IonBytes, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(1)?;
        data.ion_write(&mut e)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "ITestBlobs", "DoIt3");
        req.call::<ion_rustcore::IonBytes>(&buf).await
    }

}

/// Integer arithmetic over a fixed left-hand operand.
///
/// The operand is supplied when the client is constructed, so calling Add(2)
/// on a client created with leftOperand = 40 yields 42.
pub struct MathInteractionClient {
    ctx: ion_rustcore::IonClientContext,
}

impl ion_rustcore::FromContext for MathInteractionClient {
    fn from_context(ctx: ion_rustcore::IonClientContext) -> Self {
        Self { ctx }
    }
}

impl MathInteractionClient {
        /// Adds rightOperand to the bound operand.
    ///
    /// # Arguments
    ///
    /// * `left_operand` - The left-hand operand shared by every method on this service.
    pub async fn add(&self, left_operand: i32, right_operand: i32) -> Result<i32, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(2)?;
        left_operand.ion_write(&mut e)?;
        right_operand.ion_write(&mut e)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "IMathInteraction", "Add");
        req.call::<i32>(&buf).await
    }
    /// Multiplies the bound operand by rightOperand.
    ///
    /// # Arguments
    ///
    /// * `left_operand` - The left-hand operand shared by every method on this service.
    pub async fn mul(&self, left_operand: i32, right_operand: i32) -> Result<i32, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(2)?;
        left_operand.ion_write(&mut e)?;
        right_operand.ion_write(&mut e)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "IMathInteraction", "Mul");
        req.call::<i32>(&buf).await
    }
    /// Subtracts rightOperand from the bound operand.
    ///
    /// # Arguments
    ///
    /// * `left_operand` - The left-hand operand shared by every method on this service.
    pub async fn sub(&self, left_operand: i32, right_operand: i32) -> Result<i32, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(2)?;
        left_operand.ion_write(&mut e)?;
        right_operand.ion_write(&mut e)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "IMathInteraction", "Sub");
        req.call::<i32>(&buf).await
    }
    /// Divides the bound operand by rightOperand.
    ///
    /// Division by zero surfaces as an RPC fault, not as a return value.
    ///
    /// # Arguments
    ///
    /// * `left_operand` - The left-hand operand shared by every method on this service.
    pub async fn div(&self, left_operand: i32, right_operand: i32) -> Result<i32, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(2)?;
        left_operand.ion_write(&mut e)?;
        right_operand.ion_write(&mut e)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "IMathInteraction", "Div");
        req.call::<i32>(&buf).await
    }
    /// Raises the bound operand to the power of rightOperand.
    ///
    /// # Arguments
    ///
    /// * `left_operand` - The left-hand operand shared by every method on this service.
    pub async fn pow(&self, left_operand: i32, right_operand: i32) -> Result<i32, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(2)?;
        left_operand.ion_write(&mut e)?;
        right_operand.ion_write(&mut e)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "IMathInteraction", "Pow");
        req.call::<i32>(&buf).await
    }
    /// Raises the bound operand to each power in rightOperand, elementwise.
    ///
    /// The result array has the same length as the input array.
    ///
    /// # Arguments
    ///
    /// * `left_operand` - The left-hand operand shared by every method on this service.
    pub async fn pow_array(&self, left_operand: i32, right_operand: &Vec<i32>) -> Result<Vec<i32>, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(2)?;
        left_operand.ion_write(&mut e)?;
        ion_rustcore::formatter::write_array(&mut e, &right_operand)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "IMathInteraction", "PowArray");
        req.call::<Vec<i32>>(&buf).await
    }
    /// Returns the absolute value of rightOperand, or null when it is null.
    ///
    /// # Arguments
    ///
    /// * `left_operand` - The left-hand operand shared by every method on this service.
    pub async fn to_positive(&self, left_operand: i32, right_operand: &Option<i32>) -> Result<Option<i32>, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(2)?;
        left_operand.ion_write(&mut e)?;
        ion_rustcore::formatter::write_maybe(&mut e, &right_operand)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "IMathInteraction", "ToPositive");
        req.call_nullable::<i32>(&buf).await
    }

}

/// Deterministic pseudo-random streams seeded by the caller.
pub struct RandomStreamInteractionClient {
    ctx: ion_rustcore::IonClientContext,
}

impl ion_rustcore::FromContext for RandomStreamInteractionClient {
    fn from_context(ctx: ion_rustcore::IonClientContext) -> Self {
        Self { ctx }
    }
}

impl RandomStreamInteractionClient {
        /// Streams i pseudo-random integers derived from the seed.
    ///
    /// # Arguments
    ///
    /// * `seed` - Seed for the underlying generator. The same seed always yields the
    ///   same sequence, which is what makes the streaming tests reproducible.
    pub async fn integer(&self, seed: i32, i: i32) -> Result<ion_rustcore::IonWsStream<i32>, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(2)?;
        seed.ion_write(&mut e)?;
        i.ion_write(&mut e)?;
        let buf = e.into_writer();
        ion_rustcore::IonWsStream::open(&self.ctx, "IRandomStreamInteraction", "Integer", &buf).await
    }
    /// Bidirectional stream: every f4 pushed by the client is answered with a
    /// pseudo-random f4 derived from the seed and that input.
    ///
    /// # Arguments
    ///
    /// * `seed` - Seed for the underlying generator. The same seed always yields the
    ///   same sequence, which is what makes the streaming tests reproducible.
    pub async fn floats(&self, seed: i32) -> Result<ion_rustcore::IonWsDuplexStream<f32, f32>, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(1)?;
        seed.ion_write(&mut e)?;
        let buf = e.into_writer();
        ion_rustcore::IonWsDuplexStream::open(&self.ctx, "IRandomStreamInteraction", "Floats", &buf).await
    }

}

pub struct VectorMathInteractionClient {
    ctx: ion_rustcore::IonClientContext,
}

impl ion_rustcore::FromContext for VectorMathInteractionClient {
    fn from_context(ctx: ion_rustcore::IonClientContext) -> Self {
        Self { ctx }
    }
}

impl VectorMathInteractionClient {
        pub async fn abs(&self, left_operand: &Vector) -> Result<Vector, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(1)?;
        left_operand.ion_write(&mut e)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "IVectorMathInteraction", "Abs");
        req.call::<Vector>(&buf).await
    }
    pub async fn add(&self, left_operand: &Vector, right_operand: &Vector) -> Result<Vector, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(2)?;
        left_operand.ion_write(&mut e)?;
        right_operand.ion_write(&mut e)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "IVectorMathInteraction", "Add");
        req.call::<Vector>(&buf).await
    }
    pub async fn and_not(&self, left_operand: &Vector, right_operand: &Vector) -> Result<Vector, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(2)?;
        left_operand.ion_write(&mut e)?;
        right_operand.ion_write(&mut e)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "IVectorMathInteraction", "AndNot");
        req.call::<Vector>(&buf).await
    }
    pub async fn clamp(&self, left_operand: &Vector, min: &Vector, max: &Vector) -> Result<Vector, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(3)?;
        left_operand.ion_write(&mut e)?;
        min.ion_write(&mut e)?;
        max.ion_write(&mut e)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "IVectorMathInteraction", "Clamp");
        req.call::<Vector>(&buf).await
    }
    pub async fn r#do(&self, left_operand: &Vector) -> Result<VectorOfVectorOfVector, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(1)?;
        left_operand.ion_write(&mut e)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "IVectorMathInteraction", "Do");
        req.call::<VectorOfVectorOfVector>(&buf).await
    }

}


