//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------
import { 
  CborReader, 
  CborWriter, 
  
  DateOnly, 
  IonDateTime, 
  IonDecimal, 
  Duration, 
  TimeOnly, 
  Guid, 
  
  IonFormatterStorage,

  IonArray,
  IonMaybe,
  IonPartial,

  IIonService,
  IIonUnion,
  
  ServiceExecutor,
  IonClientContext,
  IonRequest,
  IonWsClient,
  IonInterceptor
} from "../../src";

type guid = Guid;
type timeonly = TimeOnly;
type duration = Duration;
// IonDateTime, never the deprecated `DateTimeOffset { date: Date; offsetMinutes }`
// shape: `Date` is millisecond-resolution, so it cannot hold the 100ns ticks the
// wire form carries, and the webcore "datetime" formatter now reads and writes
// IonDateTime — leaving the old alias here would be a live type mismatch, not just
// a lossy one.
type datetime = IonDateTime;
type decimal = IonDecimal;
type dateonly = DateOnly;

declare type bool = boolean;

declare type i1 = number;
declare type i2 = number;
declare type i4 = number;
declare type i8 = bigint;
declare type i16 = bigint;


declare type u1 = number;
declare type u2 = number;
declare type u4 = number;
declare type u8 = bigint;
declare type u16 = bigint;


declare type f2 = number;
declare type f4 = number;
declare type f8 = number;

export interface AppendedV1 {
  a: i4;
  b: string;
};


export interface AppendedV2 {
  a: i4;
  b: string;
  c: i4;
};


export interface InsertedV1 {
  a: i4;
  c: bool;
};


export interface InsertedV2 {
  a: i4;
  b: string;
  c: bool;
};


export interface RemovedV1 {
  a: i4;
  b: string;
  c: bool;
};


export interface RemovedV2 {
  a: i4;
  c: bool;
};


export interface ReorderedV1 {
  a: i4;
  b: string;
};


export interface ReorderedV2 {
  b: string;
  a: i4;
};


export interface RetypedV1 {
  a: i4;
  b: string;
};


export interface RetypedV2 {
  a: i4;
  b: i4;
};


export interface WidenedV1 {
  a: i4;
};


export interface WidenedV2 {
  a: i8;
};


export interface OptAddedV1 {
  a: i4;
};


export interface OptAddedV2 {
  a: i4;
  b: string | null;
};


export interface OptTightenedV1 {
  a: i4;
  b: string | null;
};


export interface OptTightenedV2 {
  a: i4;
  b: string;
};


export interface VarToFixedV1 {
  xs: IonArray<i4>;
};


export interface VarToFixedV2 {
  xs: IonArray<i4>;
};


export interface EnumHolderV1 {
  t: TierV1;
  n: i4;
};


export interface EnumHolderV2 {
  t: TierV2;
  n: i4;
};


export interface UnionHolderV1 {
  s: IShapeV1;
  n: i4;
};


export interface UnionHolderV2 {
  s: IShapeV2;
  n: i4;
};


export interface NestV1 {
  bare: AppendedV1;
  list: IonArray<AppendedV1>;
  slots: IonArray<AppendedV1>;
  byName: Map<string, AppendedV1>;
  opt: AppendedV1 | null;
  tier: TierV1;
  tiers: Set<TierV1>;
  shape: IShapeV1;
  tail: i4;
};


export interface NestV2 {
  bare: AppendedV2;
  list: IonArray<AppendedV2>;
  slots: IonArray<AppendedV2>;
  byName: Map<string, AppendedV2>;
  opt: AppendedV2 | null;
  tier: TierV2;
  tiers: Set<TierV2>;
  shape: IShapeV2;
  tail: i4;
};


export interface ShiftedV1 {
  a: i4;
  c: i4;
};


export interface ShiftedV2 {
  a: i4;
  b: i4;
  c: i4;
};


export interface SwapV1 {
  x: i4;
  y: i4;
};


export interface SwapV2 {
  y: i4;
  x: i4;
};


export interface GrowHolderV1 {
  g: IGrowV1;
  n: i4;
};


export interface GrowHolderV2 {
  g: IGrowV2;
  n: i4;
};


export interface SetHolderV1 {
  s: Set<TierV1>;
  n: i4;
};


export interface SetHolderV2 {
  s: Set<TierV2>;
  n: i4;
};


export interface TreeV1 {
  v: i4;
  kids: IonArray<TreeV1>;
};


export enum TierV1
{
  Free = 0,
  Paid = 1,
}

const declaredTierV1: ReadonlySet<unknown> = new Set<unknown>([TierV1.Free, TierV1.Paid]);

/**
 * Open-enum helpers for {@link TierV1}.
 *
 * Adding a member to an Ion enum is a safe schema change, so a value this revision does
 * not declare is decoded, carried and re-encoded verbatim rather than rejected. These
 * say whether that happened — a `switch` over the enum cannot, because an undeclared
 * value simply matches no case.
 */
export const Ion_TierV1_OpenEnum = {
  /** Whether `value` is a member this schema revision declares. */
  isKnown(value: TierV1): boolean {
    return declaredTierV1.has(value);
  },
  /**
   * The raw `u1` the peer sent when `value` names no declared member, or
   * `undefined` when it does. This is the exact value that will be written back out.
   */
  unknownValue(value: TierV1): u1 | undefined {
    return declaredTierV1.has(value) ? undefined : (value as unknown as u1);
  },
} as const;


export enum TierV2
{
  Free = 0,
  Paid = 1,
  Trial = 2,
}

const declaredTierV2: ReadonlySet<unknown> = new Set<unknown>([TierV2.Free, TierV2.Paid, TierV2.Trial]);

/**
 * Open-enum helpers for {@link TierV2}.
 *
 * Adding a member to an Ion enum is a safe schema change, so a value this revision does
 * not declare is decoded, carried and re-encoded verbatim rather than rejected. These
 * say whether that happened — a `switch` over the enum cannot, because an undeclared
 * value simply matches no case.
 */
export const Ion_TierV2_OpenEnum = {
  /** Whether `value` is a member this schema revision declares. */
  isKnown(value: TierV2): boolean {
    return declaredTierV2.has(value);
  },
  /**
   * The raw `u1` the peer sent when `value` names no declared member, or
   * `undefined` when it does. This is the exact value that will be written back out.
   */
  unknownValue(value: TierV2): u1 | undefined {
    return declaredTierV2.has(value) ? undefined : (value as unknown as u1);
  },
} as const;



export abstract class IShapeV1 implements IIonUnion<IShapeV1>
{
  abstract UnionKey: string;
  abstract UnionIndex: number;
  
  
  
  
  public isCircleV1(): this is CircleV1 {
    return this.UnionKey === "CircleV1";
  }
  public isSquareV1(): this is SquareV1 {
    return this.UnionKey === "SquareV1";
  }

}


export class CircleV1 extends IShapeV1
{
  constructor(public r: i4) { super(); }

  UnionKey: string = "CircleV1";
  UnionIndex: number = 0;
}

export class SquareV1 extends IShapeV1
{
  constructor(public s: i4) { super(); }

  UnionKey: string = "SquareV1";
  UnionIndex: number = 1;
}



IonFormatterStorage.register("IShapeV1", {
  read(reader: CborReader): IShapeV1 {
    const unionIndex = IonFormatterStorage.readStartUnion(reader, "IShapeV1", 2);
    let value: IShapeV1 = null as any;

    if (false)
    {}
        else if (unionIndex == 0)
      value = IonFormatterStorage.get<CircleV1>("CircleV1").read(reader);
    else if (unionIndex == 1)
      value = IonFormatterStorage.get<SquareV1>("SquareV1").read(reader);

    else IonFormatterStorage.invalidUnionIndex("IShapeV1", unionIndex, 2);

    IonFormatterStorage.readEndUnion(reader);
    return value!;
  },
  write(writer: CborWriter, value: IShapeV1): void {
    writer.writeStartArray(2);
    writer.writeUInt32(value.UnionIndex);
    if (false)
    {}
        else if (value.UnionIndex == 0) {
        IonFormatterStorage.get<CircleV1>("CircleV1").write(writer, value as CircleV1);
    }
    else if (value.UnionIndex == 1) {
        IonFormatterStorage.get<SquareV1>("SquareV1").write(writer, value as SquareV1);
    }
  
    else throw new Error(`Ion union 'IShapeV1' has no case ${value.UnionIndex}; this revision declares 2 case(s)`);
    writer.writeEndArray();
  }
});


IonFormatterStorage.register("CircleV1", {
  read(reader: CborReader): CircleV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 1, "CircleV1");
    const r = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 1);
    return new CircleV1(r);
  },
  write(writer: CborWriter, value: CircleV1): void {
    writer.writeStartArray(1);
    IonFormatterStorage.get<i4>('i4').write(writer, value.r);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("SquareV1", {
  read(reader: CborReader): SquareV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 1, "SquareV1");
    const s = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 1);
    return new SquareV1(s);
  },
  write(writer: CborWriter, value: SquareV1): void {
    writer.writeStartArray(1);
    IonFormatterStorage.get<i4>('i4').write(writer, value.s);
    writer.writeEndArray();
  }
});



export abstract class IShapeV2 implements IIonUnion<IShapeV2>
{
  abstract UnionKey: string;
  abstract UnionIndex: number;
  
  
  
  
  public isCircleV2(): this is CircleV2 {
    return this.UnionKey === "CircleV2";
  }
  public isSquareV2(): this is SquareV2 {
    return this.UnionKey === "SquareV2";
  }
  public isTriangleV2(): this is TriangleV2 {
    return this.UnionKey === "TriangleV2";
  }

}


export class CircleV2 extends IShapeV2
{
  constructor(public r: i4) { super(); }

  UnionKey: string = "CircleV2";
  UnionIndex: number = 0;
}

export class SquareV2 extends IShapeV2
{
  constructor(public s: i4) { super(); }

  UnionKey: string = "SquareV2";
  UnionIndex: number = 1;
}

export class TriangleV2 extends IShapeV2
{
  constructor(public t: i4) { super(); }

  UnionKey: string = "TriangleV2";
  UnionIndex: number = 2;
}



IonFormatterStorage.register("IShapeV2", {
  read(reader: CborReader): IShapeV2 {
    const unionIndex = IonFormatterStorage.readStartUnion(reader, "IShapeV2", 3);
    let value: IShapeV2 = null as any;

    if (false)
    {}
        else if (unionIndex == 0)
      value = IonFormatterStorage.get<CircleV2>("CircleV2").read(reader);
    else if (unionIndex == 1)
      value = IonFormatterStorage.get<SquareV2>("SquareV2").read(reader);
    else if (unionIndex == 2)
      value = IonFormatterStorage.get<TriangleV2>("TriangleV2").read(reader);

    else IonFormatterStorage.invalidUnionIndex("IShapeV2", unionIndex, 3);

    IonFormatterStorage.readEndUnion(reader);
    return value!;
  },
  write(writer: CborWriter, value: IShapeV2): void {
    writer.writeStartArray(2);
    writer.writeUInt32(value.UnionIndex);
    if (false)
    {}
        else if (value.UnionIndex == 0) {
        IonFormatterStorage.get<CircleV2>("CircleV2").write(writer, value as CircleV2);
    }
    else if (value.UnionIndex == 1) {
        IonFormatterStorage.get<SquareV2>("SquareV2").write(writer, value as SquareV2);
    }
    else if (value.UnionIndex == 2) {
        IonFormatterStorage.get<TriangleV2>("TriangleV2").write(writer, value as TriangleV2);
    }
  
    else throw new Error(`Ion union 'IShapeV2' has no case ${value.UnionIndex}; this revision declares 3 case(s)`);
    writer.writeEndArray();
  }
});


IonFormatterStorage.register("CircleV2", {
  read(reader: CborReader): CircleV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 1, "CircleV2");
    const r = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 1);
    return new CircleV2(r);
  },
  write(writer: CborWriter, value: CircleV2): void {
    writer.writeStartArray(1);
    IonFormatterStorage.get<i4>('i4').write(writer, value.r);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("SquareV2", {
  read(reader: CborReader): SquareV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 1, "SquareV2");
    const s = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 1);
    return new SquareV2(s);
  },
  write(writer: CborWriter, value: SquareV2): void {
    writer.writeStartArray(1);
    IonFormatterStorage.get<i4>('i4').write(writer, value.s);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("TriangleV2", {
  read(reader: CborReader): TriangleV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 1, "TriangleV2");
    const t = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 1);
    return new TriangleV2(t);
  },
  write(writer: CborWriter, value: TriangleV2): void {
    writer.writeStartArray(1);
    IonFormatterStorage.get<i4>('i4').write(writer, value.t);
    writer.writeEndArray();
  }
});



export abstract class IGrowV1 implements IIonUnion<IGrowV1>
{
  abstract UnionKey: string;
  abstract UnionIndex: number;
  
  
  
  
  public isGrowCaseV1(): this is GrowCaseV1 {
    return this.UnionKey === "GrowCaseV1";
  }

}


export class GrowCaseV1 extends IGrowV1
{
  constructor(public a: i4, public b: string) { super(); }

  UnionKey: string = "GrowCaseV1";
  UnionIndex: number = 0;
}



IonFormatterStorage.register("IGrowV1", {
  read(reader: CborReader): IGrowV1 {
    const unionIndex = IonFormatterStorage.readStartUnion(reader, "IGrowV1", 1);
    let value: IGrowV1 = null as any;

    if (false)
    {}
        else if (unionIndex == 0)
      value = IonFormatterStorage.get<GrowCaseV1>("GrowCaseV1").read(reader);

    else IonFormatterStorage.invalidUnionIndex("IGrowV1", unionIndex, 1);

    IonFormatterStorage.readEndUnion(reader);
    return value!;
  },
  write(writer: CborWriter, value: IGrowV1): void {
    writer.writeStartArray(2);
    writer.writeUInt32(value.UnionIndex);
    if (false)
    {}
        else if (value.UnionIndex == 0) {
        IonFormatterStorage.get<GrowCaseV1>("GrowCaseV1").write(writer, value as GrowCaseV1);
    }
  
    else throw new Error(`Ion union 'IGrowV1' has no case ${value.UnionIndex}; this revision declares 1 case(s)`);
    writer.writeEndArray();
  }
});


IonFormatterStorage.register("GrowCaseV1", {
  read(reader: CborReader): GrowCaseV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "GrowCaseV1");
    const a = IonFormatterStorage.get<i4>('i4').read(reader);
    const b = IonFormatterStorage.get<string>('string').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return new GrowCaseV1(a, b);
  },
  write(writer: CborWriter, value: GrowCaseV1): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<i4>('i4').write(writer, value.a);
    IonFormatterStorage.get<string>('string').write(writer, value.b);
    writer.writeEndArray();
  }
});



export abstract class IGrowV2 implements IIonUnion<IGrowV2>
{
  abstract UnionKey: string;
  abstract UnionIndex: number;
  
  
  
  
  public isGrowCaseV2(): this is GrowCaseV2 {
    return this.UnionKey === "GrowCaseV2";
  }

}


export class GrowCaseV2 extends IGrowV2
{
  constructor(public a: i4, public b: string, public c: i4) { super(); }

  UnionKey: string = "GrowCaseV2";
  UnionIndex: number = 0;
}



IonFormatterStorage.register("IGrowV2", {
  read(reader: CborReader): IGrowV2 {
    const unionIndex = IonFormatterStorage.readStartUnion(reader, "IGrowV2", 1);
    let value: IGrowV2 = null as any;

    if (false)
    {}
        else if (unionIndex == 0)
      value = IonFormatterStorage.get<GrowCaseV2>("GrowCaseV2").read(reader);

    else IonFormatterStorage.invalidUnionIndex("IGrowV2", unionIndex, 1);

    IonFormatterStorage.readEndUnion(reader);
    return value!;
  },
  write(writer: CborWriter, value: IGrowV2): void {
    writer.writeStartArray(2);
    writer.writeUInt32(value.UnionIndex);
    if (false)
    {}
        else if (value.UnionIndex == 0) {
        IonFormatterStorage.get<GrowCaseV2>("GrowCaseV2").write(writer, value as GrowCaseV2);
    }
  
    else throw new Error(`Ion union 'IGrowV2' has no case ${value.UnionIndex}; this revision declares 1 case(s)`);
    writer.writeEndArray();
  }
});


IonFormatterStorage.register("GrowCaseV2", {
  read(reader: CborReader): GrowCaseV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 3, "GrowCaseV2");
    const a = IonFormatterStorage.get<i4>('i4').read(reader);
    const b = IonFormatterStorage.get<string>('string').read(reader);
    const c = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 3);
    return new GrowCaseV2(a, b, c);
  },
  write(writer: CborWriter, value: GrowCaseV2): void {
    writer.writeStartArray(3);
    IonFormatterStorage.get<i4>('i4').write(writer, value.a);
    IonFormatterStorage.get<string>('string').write(writer, value.b);
    IonFormatterStorage.get<i4>('i4').write(writer, value.c);
    writer.writeEndArray();
  }
});



IonFormatterStorage.register("AppendedV1", {
  read(reader: CborReader): AppendedV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "AppendedV1");
    const a = IonFormatterStorage.get<i4>('i4').read(reader);
    const b = IonFormatterStorage.get<string>('string').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { a, b };
  },
  write(writer: CborWriter, value: AppendedV1): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<i4>('i4').write(writer, value.a);
    IonFormatterStorage.get<string>('string').write(writer, value.b);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("AppendedV2", {
  read(reader: CborReader): AppendedV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 3, "AppendedV2");
    const a = IonFormatterStorage.get<i4>('i4').read(reader);
    const b = IonFormatterStorage.get<string>('string').read(reader);
    const c = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 3);
    return { a, b, c };
  },
  write(writer: CborWriter, value: AppendedV2): void {
    writer.writeStartArray(3);
    IonFormatterStorage.get<i4>('i4').write(writer, value.a);
    IonFormatterStorage.get<string>('string').write(writer, value.b);
    IonFormatterStorage.get<i4>('i4').write(writer, value.c);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("InsertedV1", {
  read(reader: CborReader): InsertedV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "InsertedV1");
    const a = IonFormatterStorage.get<i4>('i4').read(reader);
    const c = IonFormatterStorage.get<bool>('bool').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { a, c };
  },
  write(writer: CborWriter, value: InsertedV1): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<i4>('i4').write(writer, value.a);
    IonFormatterStorage.get<bool>('bool').write(writer, value.c);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("InsertedV2", {
  read(reader: CborReader): InsertedV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 3, "InsertedV2");
    const a = IonFormatterStorage.get<i4>('i4').read(reader);
    const b = IonFormatterStorage.get<string>('string').read(reader);
    const c = IonFormatterStorage.get<bool>('bool').read(reader);
    reader.readEndArrayAndSkip(arraySize - 3);
    return { a, b, c };
  },
  write(writer: CborWriter, value: InsertedV2): void {
    writer.writeStartArray(3);
    IonFormatterStorage.get<i4>('i4').write(writer, value.a);
    IonFormatterStorage.get<string>('string').write(writer, value.b);
    IonFormatterStorage.get<bool>('bool').write(writer, value.c);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("RemovedV1", {
  read(reader: CborReader): RemovedV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 3, "RemovedV1");
    const a = IonFormatterStorage.get<i4>('i4').read(reader);
    const b = IonFormatterStorage.get<string>('string').read(reader);
    const c = IonFormatterStorage.get<bool>('bool').read(reader);
    reader.readEndArrayAndSkip(arraySize - 3);
    return { a, b, c };
  },
  write(writer: CborWriter, value: RemovedV1): void {
    writer.writeStartArray(3);
    IonFormatterStorage.get<i4>('i4').write(writer, value.a);
    IonFormatterStorage.get<string>('string').write(writer, value.b);
    IonFormatterStorage.get<bool>('bool').write(writer, value.c);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("RemovedV2", {
  read(reader: CborReader): RemovedV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "RemovedV2");
    const a = IonFormatterStorage.get<i4>('i4').read(reader);
    const c = IonFormatterStorage.get<bool>('bool').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { a, c };
  },
  write(writer: CborWriter, value: RemovedV2): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<i4>('i4').write(writer, value.a);
    IonFormatterStorage.get<bool>('bool').write(writer, value.c);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("ReorderedV1", {
  read(reader: CborReader): ReorderedV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "ReorderedV1");
    const a = IonFormatterStorage.get<i4>('i4').read(reader);
    const b = IonFormatterStorage.get<string>('string').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { a, b };
  },
  write(writer: CborWriter, value: ReorderedV1): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<i4>('i4').write(writer, value.a);
    IonFormatterStorage.get<string>('string').write(writer, value.b);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("ReorderedV2", {
  read(reader: CborReader): ReorderedV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "ReorderedV2");
    const b = IonFormatterStorage.get<string>('string').read(reader);
    const a = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { b, a };
  },
  write(writer: CborWriter, value: ReorderedV2): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<string>('string').write(writer, value.b);
    IonFormatterStorage.get<i4>('i4').write(writer, value.a);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("RetypedV1", {
  read(reader: CborReader): RetypedV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "RetypedV1");
    const a = IonFormatterStorage.get<i4>('i4').read(reader);
    const b = IonFormatterStorage.get<string>('string').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { a, b };
  },
  write(writer: CborWriter, value: RetypedV1): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<i4>('i4').write(writer, value.a);
    IonFormatterStorage.get<string>('string').write(writer, value.b);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("RetypedV2", {
  read(reader: CborReader): RetypedV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "RetypedV2");
    const a = IonFormatterStorage.get<i4>('i4').read(reader);
    const b = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { a, b };
  },
  write(writer: CborWriter, value: RetypedV2): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<i4>('i4').write(writer, value.a);
    IonFormatterStorage.get<i4>('i4').write(writer, value.b);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("WidenedV1", {
  read(reader: CborReader): WidenedV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 1, "WidenedV1");
    const a = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 1);
    return { a };
  },
  write(writer: CborWriter, value: WidenedV1): void {
    writer.writeStartArray(1);
    IonFormatterStorage.get<i4>('i4').write(writer, value.a);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("WidenedV2", {
  read(reader: CborReader): WidenedV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 1, "WidenedV2");
    const a = IonFormatterStorage.get<i8>('i8').read(reader);
    reader.readEndArrayAndSkip(arraySize - 1);
    return { a };
  },
  write(writer: CborWriter, value: WidenedV2): void {
    writer.writeStartArray(1);
    IonFormatterStorage.get<i8>('i8').write(writer, value.a);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("OptAddedV1", {
  read(reader: CborReader): OptAddedV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 1, "OptAddedV1");
    const a = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 1);
    return { a };
  },
  write(writer: CborWriter, value: OptAddedV1): void {
    writer.writeStartArray(1);
    IonFormatterStorage.get<i4>('i4').write(writer, value.a);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("OptAddedV2", {
  read(reader: CborReader): OptAddedV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "OptAddedV2");
    const a = IonFormatterStorage.get<i4>('i4').read(reader);
    const b = IonFormatterStorage.readNullable<string>(reader, 'string');
    reader.readEndArrayAndSkip(arraySize - 2);
    return { a, b };
  },
  write(writer: CborWriter, value: OptAddedV2): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<i4>('i4').write(writer, value.a);
    IonFormatterStorage.writeNullable<string>(writer, value.b, 'string');
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("OptTightenedV1", {
  read(reader: CborReader): OptTightenedV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "OptTightenedV1");
    const a = IonFormatterStorage.get<i4>('i4').read(reader);
    const b = IonFormatterStorage.readNullable<string>(reader, 'string');
    reader.readEndArrayAndSkip(arraySize - 2);
    return { a, b };
  },
  write(writer: CborWriter, value: OptTightenedV1): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<i4>('i4').write(writer, value.a);
    IonFormatterStorage.writeNullable<string>(writer, value.b, 'string');
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("OptTightenedV2", {
  read(reader: CborReader): OptTightenedV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "OptTightenedV2");
    const a = IonFormatterStorage.get<i4>('i4').read(reader);
    const b = IonFormatterStorage.get<string>('string').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { a, b };
  },
  write(writer: CborWriter, value: OptTightenedV2): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<i4>('i4').write(writer, value.a);
    IonFormatterStorage.get<string>('string').write(writer, value.b);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("VarToFixedV1", {
  read(reader: CborReader): VarToFixedV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 1, "VarToFixedV1");
    const xs = IonFormatterStorage.readArray<i4>(reader, 'i4');
    reader.readEndArrayAndSkip(arraySize - 1);
    return { xs };
  },
  write(writer: CborWriter, value: VarToFixedV1): void {
    writer.writeStartArray(1);
    IonFormatterStorage.writeArray<i4>(writer, value.xs, 'i4');
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("VarToFixedV2", {
  read(reader: CborReader): VarToFixedV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 1, "VarToFixedV2");
    const xs = IonFormatterStorage.readFixedArray<i4>(reader, 'i4', 3);
    reader.readEndArrayAndSkip(arraySize - 1);
    return { xs };
  },
  write(writer: CborWriter, value: VarToFixedV2): void {
    writer.writeStartArray(1);
    IonFormatterStorage.writeFixedArray<i4>(writer, value.xs, 'i4', 3);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("TierV1", {
  read(reader: CborReader): TierV1 {
    return IonFormatterStorage.readOpenEnum<TierV1>(reader, 'u1');
  },
  write(writer: CborWriter, value: TierV1): void {
    const casted: u1 = value;
    IonFormatterStorage.get<u1>('u1').write(writer, casted);
  }
});

IonFormatterStorage.register("EnumHolderV1", {
  read(reader: CborReader): EnumHolderV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "EnumHolderV1");
    const t = IonFormatterStorage.get<TierV1>('TierV1').read(reader);
    const n = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { t, n };
  },
  write(writer: CborWriter, value: EnumHolderV1): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<TierV1>('TierV1').write(writer, value.t);
    IonFormatterStorage.get<i4>('i4').write(writer, value.n);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("TierV2", {
  read(reader: CborReader): TierV2 {
    return IonFormatterStorage.readOpenEnum<TierV2>(reader, 'u1');
  },
  write(writer: CborWriter, value: TierV2): void {
    const casted: u1 = value;
    IonFormatterStorage.get<u1>('u1').write(writer, casted);
  }
});

IonFormatterStorage.register("EnumHolderV2", {
  read(reader: CborReader): EnumHolderV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "EnumHolderV2");
    const t = IonFormatterStorage.get<TierV2>('TierV2').read(reader);
    const n = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { t, n };
  },
  write(writer: CborWriter, value: EnumHolderV2): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<TierV2>('TierV2').write(writer, value.t);
    IonFormatterStorage.get<i4>('i4').write(writer, value.n);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("UnionHolderV1", {
  read(reader: CborReader): UnionHolderV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "UnionHolderV1");
    const s = IonFormatterStorage.get<IShapeV1>('IShapeV1').read(reader);
    const n = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { s, n };
  },
  write(writer: CborWriter, value: UnionHolderV1): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<IShapeV1>('IShapeV1').write(writer, value.s);
    IonFormatterStorage.get<i4>('i4').write(writer, value.n);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("UnionHolderV2", {
  read(reader: CborReader): UnionHolderV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "UnionHolderV2");
    const s = IonFormatterStorage.get<IShapeV2>('IShapeV2').read(reader);
    const n = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { s, n };
  },
  write(writer: CborWriter, value: UnionHolderV2): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<IShapeV2>('IShapeV2').write(writer, value.s);
    IonFormatterStorage.get<i4>('i4').write(writer, value.n);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("NestV1", {
  read(reader: CborReader): NestV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 9, "NestV1");
    const bare = IonFormatterStorage.get<AppendedV1>('AppendedV1').read(reader);
    const list = IonFormatterStorage.readArray<AppendedV1>(reader, 'AppendedV1');
    const slots = IonFormatterStorage.readFixedArray<AppendedV1>(reader, 'AppendedV1', 2);
    const byName = IonFormatterStorage.get<Map<string, AppendedV1>>('Map<string, AppendedV1>').read(reader);
    const opt = IonFormatterStorage.readNullable<AppendedV1>(reader, 'AppendedV1');
    const tier = IonFormatterStorage.get<TierV1>('TierV1').read(reader);
    const tiers = IonFormatterStorage.get<Set<TierV1>>('Set<TierV1>').read(reader);
    const shape = IonFormatterStorage.get<IShapeV1>('IShapeV1').read(reader);
    const tail = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 9);
    return { bare, list, slots, byName, opt, tier, tiers, shape, tail };
  },
  write(writer: CborWriter, value: NestV1): void {
    writer.writeStartArray(9);
    IonFormatterStorage.get<AppendedV1>('AppendedV1').write(writer, value.bare);
    IonFormatterStorage.writeArray<AppendedV1>(writer, value.list, 'AppendedV1');
    IonFormatterStorage.writeFixedArray<AppendedV1>(writer, value.slots, 'AppendedV1', 2);
    IonFormatterStorage.get<Map<string, AppendedV1>>('Map<string, AppendedV1>').write(writer, value.byName);
    IonFormatterStorage.writeNullable<AppendedV1>(writer, value.opt, 'AppendedV1');
    IonFormatterStorage.get<TierV1>('TierV1').write(writer, value.tier);
    IonFormatterStorage.get<Set<TierV1>>('Set<TierV1>').write(writer, value.tiers);
    IonFormatterStorage.get<IShapeV1>('IShapeV1').write(writer, value.shape);
    IonFormatterStorage.get<i4>('i4').write(writer, value.tail);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("NestV2", {
  read(reader: CborReader): NestV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 9, "NestV2");
    const bare = IonFormatterStorage.get<AppendedV2>('AppendedV2').read(reader);
    const list = IonFormatterStorage.readArray<AppendedV2>(reader, 'AppendedV2');
    const slots = IonFormatterStorage.readFixedArray<AppendedV2>(reader, 'AppendedV2', 2);
    const byName = IonFormatterStorage.get<Map<string, AppendedV2>>('Map<string, AppendedV2>').read(reader);
    const opt = IonFormatterStorage.readNullable<AppendedV2>(reader, 'AppendedV2');
    const tier = IonFormatterStorage.get<TierV2>('TierV2').read(reader);
    const tiers = IonFormatterStorage.get<Set<TierV2>>('Set<TierV2>').read(reader);
    const shape = IonFormatterStorage.get<IShapeV2>('IShapeV2').read(reader);
    const tail = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 9);
    return { bare, list, slots, byName, opt, tier, tiers, shape, tail };
  },
  write(writer: CborWriter, value: NestV2): void {
    writer.writeStartArray(9);
    IonFormatterStorage.get<AppendedV2>('AppendedV2').write(writer, value.bare);
    IonFormatterStorage.writeArray<AppendedV2>(writer, value.list, 'AppendedV2');
    IonFormatterStorage.writeFixedArray<AppendedV2>(writer, value.slots, 'AppendedV2', 2);
    IonFormatterStorage.get<Map<string, AppendedV2>>('Map<string, AppendedV2>').write(writer, value.byName);
    IonFormatterStorage.writeNullable<AppendedV2>(writer, value.opt, 'AppendedV2');
    IonFormatterStorage.get<TierV2>('TierV2').write(writer, value.tier);
    IonFormatterStorage.get<Set<TierV2>>('Set<TierV2>').write(writer, value.tiers);
    IonFormatterStorage.get<IShapeV2>('IShapeV2').write(writer, value.shape);
    IonFormatterStorage.get<i4>('i4').write(writer, value.tail);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("ShiftedV1", {
  read(reader: CborReader): ShiftedV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "ShiftedV1");
    const a = IonFormatterStorage.get<i4>('i4').read(reader);
    const c = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { a, c };
  },
  write(writer: CborWriter, value: ShiftedV1): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<i4>('i4').write(writer, value.a);
    IonFormatterStorage.get<i4>('i4').write(writer, value.c);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("ShiftedV2", {
  read(reader: CborReader): ShiftedV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 3, "ShiftedV2");
    const a = IonFormatterStorage.get<i4>('i4').read(reader);
    const b = IonFormatterStorage.get<i4>('i4').read(reader);
    const c = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 3);
    return { a, b, c };
  },
  write(writer: CborWriter, value: ShiftedV2): void {
    writer.writeStartArray(3);
    IonFormatterStorage.get<i4>('i4').write(writer, value.a);
    IonFormatterStorage.get<i4>('i4').write(writer, value.b);
    IonFormatterStorage.get<i4>('i4').write(writer, value.c);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("SwapV1", {
  read(reader: CborReader): SwapV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "SwapV1");
    const x = IonFormatterStorage.get<i4>('i4').read(reader);
    const y = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { x, y };
  },
  write(writer: CborWriter, value: SwapV1): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<i4>('i4').write(writer, value.x);
    IonFormatterStorage.get<i4>('i4').write(writer, value.y);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("SwapV2", {
  read(reader: CborReader): SwapV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "SwapV2");
    const y = IonFormatterStorage.get<i4>('i4').read(reader);
    const x = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { y, x };
  },
  write(writer: CborWriter, value: SwapV2): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<i4>('i4').write(writer, value.y);
    IonFormatterStorage.get<i4>('i4').write(writer, value.x);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("GrowHolderV1", {
  read(reader: CborReader): GrowHolderV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "GrowHolderV1");
    const g = IonFormatterStorage.get<IGrowV1>('IGrowV1').read(reader);
    const n = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { g, n };
  },
  write(writer: CborWriter, value: GrowHolderV1): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<IGrowV1>('IGrowV1').write(writer, value.g);
    IonFormatterStorage.get<i4>('i4').write(writer, value.n);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("GrowHolderV2", {
  read(reader: CborReader): GrowHolderV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "GrowHolderV2");
    const g = IonFormatterStorage.get<IGrowV2>('IGrowV2').read(reader);
    const n = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { g, n };
  },
  write(writer: CborWriter, value: GrowHolderV2): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<IGrowV2>('IGrowV2').write(writer, value.g);
    IonFormatterStorage.get<i4>('i4').write(writer, value.n);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("SetHolderV1", {
  read(reader: CborReader): SetHolderV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "SetHolderV1");
    const s = IonFormatterStorage.get<Set<TierV1>>('Set<TierV1>').read(reader);
    const n = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { s, n };
  },
  write(writer: CborWriter, value: SetHolderV1): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<Set<TierV1>>('Set<TierV1>').write(writer, value.s);
    IonFormatterStorage.get<i4>('i4').write(writer, value.n);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("SetHolderV2", {
  read(reader: CborReader): SetHolderV2 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "SetHolderV2");
    const s = IonFormatterStorage.get<Set<TierV2>>('Set<TierV2>').read(reader);
    const n = IonFormatterStorage.get<i4>('i4').read(reader);
    reader.readEndArrayAndSkip(arraySize - 2);
    return { s, n };
  },
  write(writer: CborWriter, value: SetHolderV2): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<Set<TierV2>>('Set<TierV2>').write(writer, value.s);
    IonFormatterStorage.get<i4>('i4').write(writer, value.n);
    writer.writeEndArray();
  }
});

IonFormatterStorage.register("TreeV1", {
  read(reader: CborReader): TreeV1 {
    const arraySize = IonFormatterStorage.readStartMessage(reader, 2, "TreeV1");
    const v = IonFormatterStorage.get<i4>('i4').read(reader);
    const kids = IonFormatterStorage.readArray<TreeV1>(reader, 'TreeV1');
    reader.readEndArrayAndSkip(arraySize - 2);
    return { v, kids };
  },
  write(writer: CborWriter, value: TreeV1): void {
    writer.writeStartArray(2);
    IonFormatterStorage.get<i4>('i4').write(writer, value.v);
    IonFormatterStorage.writeArray<TreeV1>(writer, value.kids, 'TreeV1');
    writer.writeEndArray();
  }
});


IonFormatterStorage.registerFixedArray<i4>("i4[3]", "i4", 3);
IonFormatterStorage.registerFixedArray<AppendedV1>("AppendedV1[2]", "AppendedV1", 2);
IonFormatterStorage.registerMap<string, AppendedV1>("Map<string, AppendedV1>", "string", "AppendedV1");
IonFormatterStorage.registerSet<TierV1>("Set<TierV1>", "TierV1");
IonFormatterStorage.registerFixedArray<AppendedV2>("AppendedV2[2]", "AppendedV2", 2);
IonFormatterStorage.registerMap<string, AppendedV2>("Map<string, AppendedV2>", "string", "AppendedV2");
IonFormatterStorage.registerSet<TierV2>("Set<TierV2>", "TierV2");



/**
 * Backward/forward compatibility probe schemas.
 *
 * Every "v1"/"v2" pair below is the SAME logical message at two schema revisions, spelled
 * with distinct names so that both revisions can be generated into one module and linked
 * into one test binary. The wire shape is what matters: a message is a positional CBOR
 * array, so a field's identity is its declaration order.
 */
export interface ICompatSvcV1 extends IIonService
{
  Echo(v: AppendedV1): Promise<AppendedV1>;
  EchoNest(v: NestV1, tail: i4): Promise<NestV1>;
}


export interface ICompatSvcV2 extends IIonService
{
  Echo(v: AppendedV2): Promise<AppendedV2>;
  EchoNest(v: NestV2, tail: i4): Promise<NestV2>;
}




/**
 * Backward/forward compatibility probe schemas.
 *
 * Every "v1"/"v2" pair below is the SAME logical message at two schema revisions, spelled
 * with distinct names so that both revisions can be generated into one module and linked
 * into one test binary. The wire shape is what matters: a message is a positional CBOR
 * array, so a field's identity is its declaration order.
 */
export interface ICompatSvcV1 extends IIonService
{
  Echo(v: AppendedV1): Promise<AppendedV1>;
  EchoNest(v: NestV1, tail: i4): Promise<NestV1>;
}


export interface ICompatSvcV2 extends IIonService
{
  Echo(v: AppendedV2): Promise<AppendedV2>;
  EchoNest(v: NestV2, tail: i4): Promise<NestV2>;
}



//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

export class CompatSvcV1_Executor extends ServiceExecutor<ICompatSvcV1> implements ICompatSvcV1 {
  constructor(public ctx: IonClientContext, private signal: AbortSignal) {
      super();
  }

  
  async Echo(v: AppendedV1): Promise<AppendedV1> {
    const req = new IonRequest(this.ctx, "ICompatSvcV1", "Echo");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(1);
          
    IonFormatterStorage.get<AppendedV1>('AppendedV1').write(writer, v);
      
    writer.writeEndArray();
          
    return await req.callAsyncT<AppendedV1>("AppendedV1", writer.data, this.signal);
  }
  async EchoNest(v: NestV1, tail: i4): Promise<NestV1> {
    const req = new IonRequest(this.ctx, "ICompatSvcV1", "EchoNest");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(2);
          
    IonFormatterStorage.get<NestV1>('NestV1').write(writer, v);
    IonFormatterStorage.get<i4>('i4').write(writer, tail);
      
    writer.writeEndArray();
          
    return await req.callAsyncT<NestV1>("NestV1", writer.data, this.signal);
  }

}

IonFormatterStorage.registerClientExecutor<ICompatSvcV1>('CompatSvcV1', CompatSvcV1_Executor);

export class CompatSvcV2_Executor extends ServiceExecutor<ICompatSvcV2> implements ICompatSvcV2 {
  constructor(public ctx: IonClientContext, private signal: AbortSignal) {
      super();
  }

  
  async Echo(v: AppendedV2): Promise<AppendedV2> {
    const req = new IonRequest(this.ctx, "ICompatSvcV2", "Echo");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(1);
          
    IonFormatterStorage.get<AppendedV2>('AppendedV2').write(writer, v);
      
    writer.writeEndArray();
          
    return await req.callAsyncT<AppendedV2>("AppendedV2", writer.data, this.signal);
  }
  async EchoNest(v: NestV2, tail: i4): Promise<NestV2> {
    const req = new IonRequest(this.ctx, "ICompatSvcV2", "EchoNest");
          
    const writer = new CborWriter();
      
    writer.writeStartArray(2);
          
    IonFormatterStorage.get<NestV2>('NestV2').write(writer, v);
    IonFormatterStorage.get<i4>('i4').write(writer, tail);
      
    writer.writeEndArray();
          
    return await req.callAsyncT<NestV2>("NestV2", writer.data, this.signal);
  }

}

IonFormatterStorage.registerClientExecutor<ICompatSvcV2>('CompatSvcV2', CompatSvcV2_Executor);


export function createClient(endpoint: string, interceptors: IonInterceptor[]) {
  const ctx = {
    baseUrl: endpoint,
    interceptors: interceptors
  } as IonClientContext;
  const controller = new AbortController();

  return new Proxy(
    {},
    {
      get(_target, propKey) {
        if (typeof propKey !== "string") return undefined;
        if (propKey === "CompatSvcV1") return IonFormatterStorage.createExecutor("CompatSvcV1", ctx, controller.signal);
        if (propKey === "CompatSvcV2") return IonFormatterStorage.createExecutor("CompatSvcV2", ctx, controller.signal);


        throw new Error(`${propKey} service is not defined`);
      },
    }
  ) as {
    CompatSvcV1: ICompatSvcV1;
    CompatSvcV2: ICompatSvcV2;

  };
}
