<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>IonPath</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#modifiers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#attributes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#entityNames</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#fieldNames</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inheritanceType</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#functionNames</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#quotedStrings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#directives</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#enumMembers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#unionCases</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>attributes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>support.function.decorator.ionpath</string>
						</dict>
					</dict>
					<key>match</key>
					<string>@([A-Za-z_][A-Za-z0-9_]*)</string>
					<key>name</key>
					<string>meta.attribute.ionpath</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>//.*$</string>
					<key>name</key>
					<string>comment.line.double-slash.ionpath</string>
				</dict>
			</array>
		</dict>
		<key>directives</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>#\b(use|feature)\b</string>
					<key>name</key>
					<string>keyword.control.directive.ionpath</string>
				</dict>
			</array>
		</dict>
		<key>entityNames</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(?&lt;=\b(msg|enum|flags|service|typedef|union)\s+)\w+\b</string>
					<key>name</key>
					<string>entity.name.type.ionpath</string>
				</dict>
			</array>
		</dict>
		<key>enumMembers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\{\s*|\s+)([A-Z][a-zA-Z0-9_]*)(?=\s*(=|,|\}))</string>
					<key>name</key>
					<string>constant.other.enum.ionpath</string>
				</dict>
			</array>
		</dict>
		<key>fieldNames</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b[a-zA-Z_][a-zA-Z0-9_]*\b(?=\s*:)</string>
					<key>name</key>
					<string>variable.other.readwrite.ionpath</string>
				</dict>
			</array>
		</dict>
		<key>functionNames</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b[a-zA-Z_][a-zA-Z0-9_]*\b(?=\s*\()</string>
					<key>name</key>
					<string>entity.name.function.ionpath</string>
				</dict>
			</array>
		</dict>
		<key>inheritanceType</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=:\s*)\b\w+\b</string>
					<key>name</key>
					<string>storage.type.ionpath</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(msg|flags|enum|typedef|service|union|attribute|#use|#feature)\b</string>
					<key>name</key>
					<string>keyword.control.ionpath</string>
				</dict>
			</array>
		</dict>
		<key>modifiers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(stream|unary|internal)\b</string>
					<key>name</key>
					<string>storage.modifier.ionpath</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b\d+(?:\s*&lt;&lt;\s*\d+)?\b</string>
					<key>name</key>
					<string>constant.numeric.ionpath</string>
				</dict>
			</array>
		</dict>
		<key>quotedStrings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>'</string>
					<key>end</key>
					<string>'</string>
					<key>name</key>
					<string>string.quoted.single.ionpath</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.ionpath</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>"</string>
					<key>end</key>
					<string>"</string>
					<key>name</key>
					<string>string.quoted.double.ionpath</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>\\.</string>
							<key>name</key>
							<string>constant.character.escape.ionpath</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(i8|i16|i32|i64|u8|u16|u32|u64|f32|f64|bool|string|guid)\b</string>
					<key>name</key>
					<string>storage.type.ionpath</string>
				</dict>
			</array>
		</dict>
		<key>unionCases</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(?&lt;=\{\s*|\s+)([A-Z][a-zA-Z0-9_]*)(?=\s*\()</string>
					<key>name</key>
					<string>entity.name.unioncase.ionpath</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.ion</string>
</dict>
</plist>
