//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace IonCompat;
// Backward/forward compatibility probe schemas.
//
// Every "v1"/"v2" pair below is the SAME logical message at two schema revisions, spelled
// with distinct names so that both revisions can be generated into one module and linked
// into one test binary. The wire shape is what matters: a message is a positional CBOR
// array, so a field's identity is its declaration order.

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record AppendedV1(i4 a, string b);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record AppendedV2(i4 a, string b, i4 c);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record InsertedV1(i4 a, bool c);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record InsertedV2(i4 a, string b, bool c);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record RemovedV1(i4 a, string b, bool c);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record RemovedV2(i4 a, bool c);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record ReorderedV1(i4 a, string b);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record ReorderedV2(string b, i4 a);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record RetypedV1(i4 a, string b);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record RetypedV2(i4 a, i4 b);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record WidenedV1(i4 a);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record WidenedV2(i8 a);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record OptAddedV1(i4 a);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record OptAddedV2(i4 a, string? b);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record OptTightenedV1(i4 a, string? b);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record OptTightenedV2(i4 a, string b);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record VarToFixedV1(IonArray<i4> xs);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record VarToFixedV2(IonArray<i4> xs);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record EnumHolderV1(TierV1 t, i4 n);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record EnumHolderV2(TierV2 t, i4 n);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record UnionHolderV1(IShapeV1 s, i4 n);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record UnionHolderV2(IShapeV2 s, i4 n);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record NestV1(AppendedV1 bare, IonArray<AppendedV1> list, IonArray<AppendedV1> slots, Dictionary<string, AppendedV1> byName, AppendedV1? opt, TierV1 tier, HashSet<TierV1> tiers, IShapeV1 shape, i4 tail);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record NestV2(AppendedV2 bare, IonArray<AppendedV2> list, IonArray<AppendedV2> slots, Dictionary<string, AppendedV2> byName, AppendedV2? opt, TierV2 tier, HashSet<TierV2> tiers, IShapeV2 shape, i4 tail);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record ShiftedV1(i4 a, i4 c);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record ShiftedV2(i4 a, i4 b, i4 c);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record SwapV1(i4 x, i4 y);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record SwapV2(i4 y, i4 x);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record GrowHolderV1(IGrowV1 g, i4 n);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record GrowHolderV2(IGrowV2 g, i4 n);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record SetHolderV1(HashSet<TierV1> s, i4 n);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record SetHolderV2(HashSet<TierV2> s, i4 n);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record TreeV1(i4 v, IonArray<TreeV1> kids);


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public enum TierV1 : u1
{
    Free = 0,
    Paid = 1,
}

/// <summary>Open-enum helpers for <see cref="TierV1"/>.</summary>
/// <remarks>
/// A value the peer's schema declares and this one does not is carried through decoding
/// rather than rejected, so that adding a member stays a safe schema change. These say
/// whether that happened — a <c>switch</c> over the enum cannot, because an undeclared
/// value simply matches no arm.
/// </remarks>
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public static class Ion_TierV1_OpenEnum
{
    /// <summary>Whether <paramref name="value"/> is a member this schema revision declares.</summary>
    public static bool IsKnown(this TierV1 value)
        => value == TierV1.Free || value == TierV1.Paid;

    /// <summary>
    /// The raw <c>u1</c> the peer sent when <paramref name="value"/> names no
    /// declared member, or <see langword="null"/> when it does.
    /// </summary>
    /// <remarks>This is the exact number that will be written back out.</remarks>
    public static u1? UnknownValue(this TierV1 value)
        => value.IsKnown() ? null : (u1)value;
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public enum TierV2 : u1
{
    Free = 0,
    Paid = 1,
    Trial = 2,
}

/// <summary>Open-enum helpers for <see cref="TierV2"/>.</summary>
/// <remarks>
/// A value the peer's schema declares and this one does not is carried through decoding
/// rather than rejected, so that adding a member stays a safe schema change. These say
/// whether that happened — a <c>switch</c> over the enum cannot, because an undeclared
/// value simply matches no arm.
/// </remarks>
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public static class Ion_TierV2_OpenEnum
{
    /// <summary>Whether <paramref name="value"/> is a member this schema revision declares.</summary>
    public static bool IsKnown(this TierV2 value)
        => value == TierV2.Free || value == TierV2.Paid || value == TierV2.Trial;

    /// <summary>
    /// The raw <c>u1</c> the peer sent when <paramref name="value"/> names no
    /// declared member, or <see langword="null"/> when it does.
    /// </summary>
    /// <remarks>This is the exact number that will be written back out.</remarks>
    public static u1? UnknownValue(this TierV2 value)
        => value.IsKnown() ? null : (u1)value;
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface ICompatSvcV1 : IIonService
{
    Task<AppendedV1> Echo(AppendedV1 v, CancellationToken ct = default);
    Task<NestV1> EchoNest(NestV1 v, i4 tail, CancellationToken ct = default);
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface ICompatSvcV2 : IIonService
{
    Task<AppendedV2> Echo(AppendedV2 v, CancellationToken ct = default);
    Task<NestV2> EchoNest(NestV2 v, i4 tail, CancellationToken ct = default);
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface IShapeV1 : IIonUnion<IShapeV1>
{
    string UnionKey { get; }
    uint UnionIndex { get; }
    
    
    internal bool IsCircleV1 => this is CircleV1;

    internal bool IsSquareV1 => this is SquareV1;

}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record CircleV1(i4 r) : IShapeV1
{
    public string UnionKey => nameof(CircleV1);
    public uint UnionIndex => 0;
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record SquareV1(i4 s) : IShapeV1
{
    public string UnionKey => nameof(SquareV1);
    public uint UnionIndex => 1;
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_IShapeV1_Formatter : IonFormatter<IShapeV1>
{
    public IShapeV1 Read(CborReader reader)
    {
        var unionIndex = reader.ReadStartUnion("IShapeV1", 2u);
        IShapeV1 result;
        if (false) {}
        
        else if (unionIndex == 0)
            result = IonFormatterStorage<CircleV1>.Read(reader);

        else if (unionIndex == 1)
            result = IonFormatterStorage<SquareV1>.Read(reader);

        else
            throw new IonInvalidUnionIndexException("IShapeV1", unionIndex, 2u);
        reader.ReadEndUnion();
        return result;
    }

    public void Write(CborWriter writer, IShapeV1 value)
    {
        writer.WriteStartArray(2);
        writer.WriteUInt32(value.UnionIndex);

        if (false) {}
        
        else if (value is CircleV1 n_0)
        {
            if (n_0.UnionIndex != 0)
                throw new InvalidOperationException();
            IonFormatterStorage<CircleV1>.Write(writer, n_0);
        }

        else if (value is SquareV1 n_1)
        {
            if (n_1.UnionIndex != 1)
                throw new InvalidOperationException();
            IonFormatterStorage<SquareV1>.Write(writer, n_1);
        }
    
        else
            throw new InvalidOperationException(
                $"Ion union 'IShapeV1' has no case {value.UnionIndex}; this revision declares 2 case(s)");
        writer.WriteEndArray();    
    }
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_CircleV1_Formatter : IonFormatter<CircleV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public CircleV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "CircleV1");
        var __r = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__r);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, CircleV1 value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<i4>.Write(writer, value.r);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_SquareV1_Formatter : IonFormatter<SquareV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public SquareV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "SquareV1");
        var __s = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__s);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, SquareV1 value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<i4>.Write(writer, value.s);
        writer.WriteEndArray();
    }
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface IShapeV2 : IIonUnion<IShapeV2>
{
    string UnionKey { get; }
    uint UnionIndex { get; }
    
    
    internal bool IsCircleV2 => this is CircleV2;

    internal bool IsSquareV2 => this is SquareV2;

    internal bool IsTriangleV2 => this is TriangleV2;

}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record CircleV2(i4 r) : IShapeV2
{
    public string UnionKey => nameof(CircleV2);
    public uint UnionIndex => 0;
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record SquareV2(i4 s) : IShapeV2
{
    public string UnionKey => nameof(SquareV2);
    public uint UnionIndex => 1;
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record TriangleV2(i4 t) : IShapeV2
{
    public string UnionKey => nameof(TriangleV2);
    public uint UnionIndex => 2;
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_IShapeV2_Formatter : IonFormatter<IShapeV2>
{
    public IShapeV2 Read(CborReader reader)
    {
        var unionIndex = reader.ReadStartUnion("IShapeV2", 3u);
        IShapeV2 result;
        if (false) {}
        
        else if (unionIndex == 0)
            result = IonFormatterStorage<CircleV2>.Read(reader);

        else if (unionIndex == 1)
            result = IonFormatterStorage<SquareV2>.Read(reader);

        else if (unionIndex == 2)
            result = IonFormatterStorage<TriangleV2>.Read(reader);

        else
            throw new IonInvalidUnionIndexException("IShapeV2", unionIndex, 3u);
        reader.ReadEndUnion();
        return result;
    }

    public void Write(CborWriter writer, IShapeV2 value)
    {
        writer.WriteStartArray(2);
        writer.WriteUInt32(value.UnionIndex);

        if (false) {}
        
        else if (value is CircleV2 n_0)
        {
            if (n_0.UnionIndex != 0)
                throw new InvalidOperationException();
            IonFormatterStorage<CircleV2>.Write(writer, n_0);
        }

        else if (value is SquareV2 n_1)
        {
            if (n_1.UnionIndex != 1)
                throw new InvalidOperationException();
            IonFormatterStorage<SquareV2>.Write(writer, n_1);
        }

        else if (value is TriangleV2 n_2)
        {
            if (n_2.UnionIndex != 2)
                throw new InvalidOperationException();
            IonFormatterStorage<TriangleV2>.Write(writer, n_2);
        }
    
        else
            throw new InvalidOperationException(
                $"Ion union 'IShapeV2' has no case {value.UnionIndex}; this revision declares 3 case(s)");
        writer.WriteEndArray();    
    }
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_CircleV2_Formatter : IonFormatter<CircleV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public CircleV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "CircleV2");
        var __r = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__r);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, CircleV2 value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<i4>.Write(writer, value.r);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_SquareV2_Formatter : IonFormatter<SquareV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public SquareV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "SquareV2");
        var __s = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__s);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, SquareV2 value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<i4>.Write(writer, value.s);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_TriangleV2_Formatter : IonFormatter<TriangleV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public TriangleV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "TriangleV2");
        var __t = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__t);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, TriangleV2 value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<i4>.Write(writer, value.t);
        writer.WriteEndArray();
    }
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface IGrowV1 : IIonUnion<IGrowV1>
{
    string UnionKey { get; }
    uint UnionIndex { get; }
    
    
    internal bool IsGrowCaseV1 => this is GrowCaseV1;

}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record GrowCaseV1(i4 a, string b) : IGrowV1
{
    public string UnionKey => nameof(GrowCaseV1);
    public uint UnionIndex => 0;
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_IGrowV1_Formatter : IonFormatter<IGrowV1>
{
    public IGrowV1 Read(CborReader reader)
    {
        var unionIndex = reader.ReadStartUnion("IGrowV1", 1u);
        IGrowV1 result;
        if (false) {}
        
        else if (unionIndex == 0)
            result = IonFormatterStorage<GrowCaseV1>.Read(reader);

        else
            throw new IonInvalidUnionIndexException("IGrowV1", unionIndex, 1u);
        reader.ReadEndUnion();
        return result;
    }

    public void Write(CborWriter writer, IGrowV1 value)
    {
        writer.WriteStartArray(2);
        writer.WriteUInt32(value.UnionIndex);

        if (false) {}
        
        else if (value is GrowCaseV1 n_0)
        {
            if (n_0.UnionIndex != 0)
                throw new InvalidOperationException();
            IonFormatterStorage<GrowCaseV1>.Write(writer, n_0);
        }
    
        else
            throw new InvalidOperationException(
                $"Ion union 'IGrowV1' has no case {value.UnionIndex}; this revision declares 1 case(s)");
        writer.WriteEndArray();    
    }
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_GrowCaseV1_Formatter : IonFormatter<GrowCaseV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public GrowCaseV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "GrowCaseV1");
        var __a = IonFormatterStorage<i4>.Read(reader);
        var __b = IonFormatterStorage<string>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__a, __b);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, GrowCaseV1 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<i4>.Write(writer, value.a);
        IonFormatterStorage<string>.Write(writer, value.b);
        writer.WriteEndArray();
    }
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public interface IGrowV2 : IIonUnion<IGrowV2>
{
    string UnionKey { get; }
    uint UnionIndex { get; }
    
    
    internal bool IsGrowCaseV2 => this is GrowCaseV2;

}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed record GrowCaseV2(i4 a, string b, i4 c) : IGrowV2
{
    public string UnionKey => nameof(GrowCaseV2);
    public uint UnionIndex => 0;
}



[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_IGrowV2_Formatter : IonFormatter<IGrowV2>
{
    public IGrowV2 Read(CborReader reader)
    {
        var unionIndex = reader.ReadStartUnion("IGrowV2", 1u);
        IGrowV2 result;
        if (false) {}
        
        else if (unionIndex == 0)
            result = IonFormatterStorage<GrowCaseV2>.Read(reader);

        else
            throw new IonInvalidUnionIndexException("IGrowV2", unionIndex, 1u);
        reader.ReadEndUnion();
        return result;
    }

    public void Write(CborWriter writer, IGrowV2 value)
    {
        writer.WriteStartArray(2);
        writer.WriteUInt32(value.UnionIndex);

        if (false) {}
        
        else if (value is GrowCaseV2 n_0)
        {
            if (n_0.UnionIndex != 0)
                throw new InvalidOperationException();
            IonFormatterStorage<GrowCaseV2>.Write(writer, n_0);
        }
    
        else
            throw new InvalidOperationException(
                $"Ion union 'IGrowV2' has no case {value.UnionIndex}; this revision declares 1 case(s)");
        writer.WriteEndArray();    
    }
}


[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_GrowCaseV2_Formatter : IonFormatter<GrowCaseV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public GrowCaseV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(3, "GrowCaseV2");
        var __a = IonFormatterStorage<i4>.Read(reader);
        var __b = IonFormatterStorage<string>.Read(reader);
        var __c = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 3);
        return new(__a, __b, __c);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, GrowCaseV2 value)
    {
        writer.WriteStartArray(3);
        IonFormatterStorage<i4>.Write(writer, value.a);
        IonFormatterStorage<string>.Write(writer, value.b);
        IonFormatterStorage<i4>.Write(writer, value.c);
        writer.WriteEndArray();
    }
}


