//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace IonCompat;
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_AppendedV1_Formatter : IonFormatter<AppendedV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public AppendedV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "AppendedV1");
        var __a = IonFormatterStorage<i4>.Read(reader);
        var __b = IonFormatterStorage<string>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__a, __b);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, AppendedV1 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<i4>.Write(writer, value.a);
        IonFormatterStorage<string>.Write(writer, value.b);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_AppendedV2_Formatter : IonFormatter<AppendedV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public AppendedV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(3, "AppendedV2");
        var __a = IonFormatterStorage<i4>.Read(reader);
        var __b = IonFormatterStorage<string>.Read(reader);
        var __c = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 3);
        return new(__a, __b, __c);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, AppendedV2 value)
    {
        writer.WriteStartArray(3);
        IonFormatterStorage<i4>.Write(writer, value.a);
        IonFormatterStorage<string>.Write(writer, value.b);
        IonFormatterStorage<i4>.Write(writer, value.c);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_InsertedV1_Formatter : IonFormatter<InsertedV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public InsertedV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "InsertedV1");
        var __a = IonFormatterStorage<i4>.Read(reader);
        var __c = IonFormatterStorage<bool>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__a, __c);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, InsertedV1 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<i4>.Write(writer, value.a);
        IonFormatterStorage<bool>.Write(writer, value.c);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_InsertedV2_Formatter : IonFormatter<InsertedV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public InsertedV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(3, "InsertedV2");
        var __a = IonFormatterStorage<i4>.Read(reader);
        var __b = IonFormatterStorage<string>.Read(reader);
        var __c = IonFormatterStorage<bool>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 3);
        return new(__a, __b, __c);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, InsertedV2 value)
    {
        writer.WriteStartArray(3);
        IonFormatterStorage<i4>.Write(writer, value.a);
        IonFormatterStorage<string>.Write(writer, value.b);
        IonFormatterStorage<bool>.Write(writer, value.c);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_RemovedV1_Formatter : IonFormatter<RemovedV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public RemovedV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(3, "RemovedV1");
        var __a = IonFormatterStorage<i4>.Read(reader);
        var __b = IonFormatterStorage<string>.Read(reader);
        var __c = IonFormatterStorage<bool>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 3);
        return new(__a, __b, __c);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, RemovedV1 value)
    {
        writer.WriteStartArray(3);
        IonFormatterStorage<i4>.Write(writer, value.a);
        IonFormatterStorage<string>.Write(writer, value.b);
        IonFormatterStorage<bool>.Write(writer, value.c);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_RemovedV2_Formatter : IonFormatter<RemovedV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public RemovedV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "RemovedV2");
        var __a = IonFormatterStorage<i4>.Read(reader);
        var __c = IonFormatterStorage<bool>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__a, __c);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, RemovedV2 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<i4>.Write(writer, value.a);
        IonFormatterStorage<bool>.Write(writer, value.c);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_ReorderedV1_Formatter : IonFormatter<ReorderedV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public ReorderedV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "ReorderedV1");
        var __a = IonFormatterStorage<i4>.Read(reader);
        var __b = IonFormatterStorage<string>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__a, __b);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, ReorderedV1 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<i4>.Write(writer, value.a);
        IonFormatterStorage<string>.Write(writer, value.b);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_ReorderedV2_Formatter : IonFormatter<ReorderedV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public ReorderedV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "ReorderedV2");
        var __b = IonFormatterStorage<string>.Read(reader);
        var __a = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__b, __a);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, ReorderedV2 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<string>.Write(writer, value.b);
        IonFormatterStorage<i4>.Write(writer, value.a);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_RetypedV1_Formatter : IonFormatter<RetypedV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public RetypedV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "RetypedV1");
        var __a = IonFormatterStorage<i4>.Read(reader);
        var __b = IonFormatterStorage<string>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__a, __b);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, RetypedV1 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<i4>.Write(writer, value.a);
        IonFormatterStorage<string>.Write(writer, value.b);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_RetypedV2_Formatter : IonFormatter<RetypedV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public RetypedV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "RetypedV2");
        var __a = IonFormatterStorage<i4>.Read(reader);
        var __b = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__a, __b);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, RetypedV2 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<i4>.Write(writer, value.a);
        IonFormatterStorage<i4>.Write(writer, value.b);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_WidenedV1_Formatter : IonFormatter<WidenedV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public WidenedV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "WidenedV1");
        var __a = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__a);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, WidenedV1 value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<i4>.Write(writer, value.a);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_WidenedV2_Formatter : IonFormatter<WidenedV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public WidenedV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "WidenedV2");
        var __a = IonFormatterStorage<i8>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__a);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, WidenedV2 value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<i8>.Write(writer, value.a);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_OptAddedV1_Formatter : IonFormatter<OptAddedV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public OptAddedV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "OptAddedV1");
        var __a = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__a);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, OptAddedV1 value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<i4>.Write(writer, value.a);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_OptAddedV2_Formatter : IonFormatter<OptAddedV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public OptAddedV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "OptAddedV2");
        var __a = IonFormatterStorage<i4>.Read(reader);
        var __b = reader.ReadNullable<string>();
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__a, __b);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, OptAddedV2 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<i4>.Write(writer, value.a);
        IonFormatterStorage<string>.WriteNullable(writer, value.b);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_OptTightenedV1_Formatter : IonFormatter<OptTightenedV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public OptTightenedV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "OptTightenedV1");
        var __a = IonFormatterStorage<i4>.Read(reader);
        var __b = reader.ReadNullable<string>();
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__a, __b);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, OptTightenedV1 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<i4>.Write(writer, value.a);
        IonFormatterStorage<string>.WriteNullable(writer, value.b);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_OptTightenedV2_Formatter : IonFormatter<OptTightenedV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public OptTightenedV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "OptTightenedV2");
        var __a = IonFormatterStorage<i4>.Read(reader);
        var __b = IonFormatterStorage<string>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__a, __b);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, OptTightenedV2 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<i4>.Write(writer, value.a);
        IonFormatterStorage<string>.Write(writer, value.b);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_VarToFixedV1_Formatter : IonFormatter<VarToFixedV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public VarToFixedV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "VarToFixedV1");
        var __xs = IonFormatterStorage<i4>.ReadArray(reader);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__xs);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, VarToFixedV1 value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<i4>.WriteArray(writer, value.xs);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_VarToFixedV2_Formatter : IonFormatter<VarToFixedV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public VarToFixedV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(1, "VarToFixedV2");
        var __xs = IonFormatterStorage<i4>.ReadFixedArray(reader, 3);
        reader.ReadEndArrayAndSkip(arraySize - 1);
        return new(__xs);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, VarToFixedV2 value)
    {
        writer.WriteStartArray(1);
        IonFormatterStorage<i4>.WriteFixedArray(writer, value.xs, 3);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_EnumHolderV1_Formatter : IonFormatter<EnumHolderV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public EnumHolderV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "EnumHolderV1");
        var __t = IonFormatterStorage<TierV1>.Read(reader);
        var __n = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__t, __n);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, EnumHolderV1 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<TierV1>.Write(writer, value.t);
        IonFormatterStorage<i4>.Write(writer, value.n);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_EnumHolderV2_Formatter : IonFormatter<EnumHolderV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public EnumHolderV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "EnumHolderV2");
        var __t = IonFormatterStorage<TierV2>.Read(reader);
        var __n = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__t, __n);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, EnumHolderV2 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<TierV2>.Write(writer, value.t);
        IonFormatterStorage<i4>.Write(writer, value.n);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_UnionHolderV1_Formatter : IonFormatter<UnionHolderV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public UnionHolderV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "UnionHolderV1");
        var __s = IonFormatterStorage<IShapeV1>.Read(reader);
        var __n = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__s, __n);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, UnionHolderV1 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<IShapeV1>.Write(writer, value.s);
        IonFormatterStorage<i4>.Write(writer, value.n);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_UnionHolderV2_Formatter : IonFormatter<UnionHolderV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public UnionHolderV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "UnionHolderV2");
        var __s = IonFormatterStorage<IShapeV2>.Read(reader);
        var __n = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__s, __n);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, UnionHolderV2 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<IShapeV2>.Write(writer, value.s);
        IonFormatterStorage<i4>.Write(writer, value.n);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_NestV1_Formatter : IonFormatter<NestV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public NestV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(9, "NestV1");
        var __bare = IonFormatterStorage<AppendedV1>.Read(reader);
        var __list = IonFormatterStorage<AppendedV1>.ReadArray(reader);
        var __slots = IonFormatterStorage<AppendedV1>.ReadFixedArray(reader, 2);
        var __byname = IonFormatterStorage<Dictionary<string, AppendedV1>>.Read(reader);
        var __opt = reader.ReadNullable<AppendedV1>();
        var __tier = IonFormatterStorage<TierV1>.Read(reader);
        var __tiers = IonFormatterStorage<HashSet<TierV1>>.Read(reader);
        var __shape = IonFormatterStorage<IShapeV1>.Read(reader);
        var __tail = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 9);
        return new(__bare, __list, __slots, __byname, __opt, __tier, __tiers, __shape, __tail);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, NestV1 value)
    {
        writer.WriteStartArray(9);
        IonFormatterStorage<AppendedV1>.Write(writer, value.bare);
        IonFormatterStorage<AppendedV1>.WriteArray(writer, value.list);
        IonFormatterStorage<AppendedV1>.WriteFixedArray(writer, value.slots, 2);
        IonFormatterStorage<Dictionary<string, AppendedV1>>.Write(writer, value.byName);
        IonFormatterStorage<AppendedV1>.WriteNullable(writer, value.opt);
        IonFormatterStorage<TierV1>.Write(writer, value.tier);
        IonFormatterStorage<HashSet<TierV1>>.Write(writer, value.tiers);
        IonFormatterStorage<IShapeV1>.Write(writer, value.shape);
        IonFormatterStorage<i4>.Write(writer, value.tail);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_NestV2_Formatter : IonFormatter<NestV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public NestV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(9, "NestV2");
        var __bare = IonFormatterStorage<AppendedV2>.Read(reader);
        var __list = IonFormatterStorage<AppendedV2>.ReadArray(reader);
        var __slots = IonFormatterStorage<AppendedV2>.ReadFixedArray(reader, 2);
        var __byname = IonFormatterStorage<Dictionary<string, AppendedV2>>.Read(reader);
        var __opt = reader.ReadNullable<AppendedV2>();
        var __tier = IonFormatterStorage<TierV2>.Read(reader);
        var __tiers = IonFormatterStorage<HashSet<TierV2>>.Read(reader);
        var __shape = IonFormatterStorage<IShapeV2>.Read(reader);
        var __tail = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 9);
        return new(__bare, __list, __slots, __byname, __opt, __tier, __tiers, __shape, __tail);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, NestV2 value)
    {
        writer.WriteStartArray(9);
        IonFormatterStorage<AppendedV2>.Write(writer, value.bare);
        IonFormatterStorage<AppendedV2>.WriteArray(writer, value.list);
        IonFormatterStorage<AppendedV2>.WriteFixedArray(writer, value.slots, 2);
        IonFormatterStorage<Dictionary<string, AppendedV2>>.Write(writer, value.byName);
        IonFormatterStorage<AppendedV2>.WriteNullable(writer, value.opt);
        IonFormatterStorage<TierV2>.Write(writer, value.tier);
        IonFormatterStorage<HashSet<TierV2>>.Write(writer, value.tiers);
        IonFormatterStorage<IShapeV2>.Write(writer, value.shape);
        IonFormatterStorage<i4>.Write(writer, value.tail);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_ShiftedV1_Formatter : IonFormatter<ShiftedV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public ShiftedV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "ShiftedV1");
        var __a = IonFormatterStorage<i4>.Read(reader);
        var __c = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__a, __c);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, ShiftedV1 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<i4>.Write(writer, value.a);
        IonFormatterStorage<i4>.Write(writer, value.c);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_ShiftedV2_Formatter : IonFormatter<ShiftedV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public ShiftedV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(3, "ShiftedV2");
        var __a = IonFormatterStorage<i4>.Read(reader);
        var __b = IonFormatterStorage<i4>.Read(reader);
        var __c = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 3);
        return new(__a, __b, __c);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, ShiftedV2 value)
    {
        writer.WriteStartArray(3);
        IonFormatterStorage<i4>.Write(writer, value.a);
        IonFormatterStorage<i4>.Write(writer, value.b);
        IonFormatterStorage<i4>.Write(writer, value.c);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_SwapV1_Formatter : IonFormatter<SwapV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public SwapV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "SwapV1");
        var __x = IonFormatterStorage<i4>.Read(reader);
        var __y = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__x, __y);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, SwapV1 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<i4>.Write(writer, value.x);
        IonFormatterStorage<i4>.Write(writer, value.y);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_SwapV2_Formatter : IonFormatter<SwapV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public SwapV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "SwapV2");
        var __y = IonFormatterStorage<i4>.Read(reader);
        var __x = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__y, __x);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, SwapV2 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<i4>.Write(writer, value.y);
        IonFormatterStorage<i4>.Write(writer, value.x);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_GrowHolderV1_Formatter : IonFormatter<GrowHolderV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public GrowHolderV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "GrowHolderV1");
        var __g = IonFormatterStorage<IGrowV1>.Read(reader);
        var __n = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__g, __n);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, GrowHolderV1 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<IGrowV1>.Write(writer, value.g);
        IonFormatterStorage<i4>.Write(writer, value.n);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_GrowHolderV2_Formatter : IonFormatter<GrowHolderV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public GrowHolderV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "GrowHolderV2");
        var __g = IonFormatterStorage<IGrowV2>.Read(reader);
        var __n = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__g, __n);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, GrowHolderV2 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<IGrowV2>.Write(writer, value.g);
        IonFormatterStorage<i4>.Write(writer, value.n);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_SetHolderV1_Formatter : IonFormatter<SetHolderV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public SetHolderV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "SetHolderV1");
        var __s = IonFormatterStorage<HashSet<TierV1>>.Read(reader);
        var __n = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__s, __n);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, SetHolderV1 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<HashSet<TierV1>>.Write(writer, value.s);
        IonFormatterStorage<i4>.Write(writer, value.n);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_SetHolderV2_Formatter : IonFormatter<SetHolderV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public SetHolderV2 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "SetHolderV2");
        var __s = IonFormatterStorage<HashSet<TierV2>>.Read(reader);
        var __n = IonFormatterStorage<i4>.Read(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__s, __n);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, SetHolderV2 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<HashSet<TierV2>>.Write(writer, value.s);
        IonFormatterStorage<i4>.Write(writer, value.n);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_TreeV1_Formatter : IonFormatter<TreeV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public TreeV1 Read(CborReader reader)
    {
        var arraySize = reader.ReadStartMessage(2, "TreeV1");
        var __v = IonFormatterStorage<i4>.Read(reader);
        var __kids = IonFormatterStorage<TreeV1>.ReadArray(reader);
        reader.ReadEndArrayAndSkip(arraySize - 2);
        return new(__v, __kids);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, TreeV1 value)
    {
        writer.WriteStartArray(2);
        IonFormatterStorage<i4>.Write(writer, value.v);
        IonFormatterStorage<TreeV1>.WriteArray(writer, value.kids);
        writer.WriteEndArray();
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_TierV1_Formatter : IonFormatter<TierV1>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public TierV1 Read(CborReader reader)
    {
         return (TierV1)(IonFormatterStorage<u1>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, TierV1 value)
    {
        var casted = (u1)value;
        IonFormatterStorage<u1>.Write(writer, casted);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_TierV2_Formatter : IonFormatter<TierV2>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public TierV2 Read(CborReader reader)
    {
         return (TierV2)(IonFormatterStorage<u1>.Read(reader));
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, TierV2 value)
    {
        var casted = (u1)value;
        IonFormatterStorage<u1>.Write(writer, casted);
    }
}

