namespace ion.compiler.CodeGen;

using ion.runtime;
using syntax;
using System.Text;

public class IonTypeScriptGenerator(string @namespace) : IIonCodeGenerator
{
    public static bool UseMaybeWrapper { get; set; }

    public string FileHeader()
    {
        return $"""
                //------------------------------------------------------------------------------
                // <auto-generated>
                //     This code was generated by a code generation tool.
                //     Changes to this file may cause incorrect behavior and will be lost
                //     if the code is regenerated.
                //
                //     Generator: IonPath Codegen
                // </auto-generated>
                //------------------------------------------------------------------------------
                """;
    }

    public void GenerateProjectFile(string projectName, FileInfo outputFile)
    {
        throw new NotImplementedException();
    }

    public string GenerateModuleInit(IEnumerable<IonType> types, IReadOnlyList<IonService> services, bool clientToo,
        bool serverToo)
    {
        throw new NotImplementedException();
    }

    public string GenerateModule(IonModule module)
    {
        throw new NotImplementedException();
    }

    public string GenerateAllServiceExecutors(IEnumerable<IonService> service)
    {
        throw new NotImplementedException();
    }

    public string GenerateTypes(IEnumerable<IonType> types)
    {
        var sb = new StringBuilder();
        sb.AppendLine();

        var allTypes = types.ToList();

        // Typedefs first so an alias is declared ahead of the interfaces that mention it.
        foreach (var type in allTypes.Where(type => type is { IsUnionCase: false, IsUnion: false })
                     .OrderBy(type => IsTypedefDeclaration(type) ? 0 : 1))
        {
            sb.AppendLine(GenerateType(type));
            sb.AppendLine();
        }

        foreach (var union in allTypes.OfType<IonUnion>())
        {
            sb.AppendLine(GenerateUnion(union));
            sb.AppendLine();
        }

        return sb.ToString();
    }

    public string GenerateServices(IonModule module)
    {
        var sb = new StringBuilder();
        sb.AppendLine();

        // Module level documentation. The browser target emits one bundled file assembled by
        // the compile command, so the closest place a module is still identifiable is here,
        // at the head of its service section.
        sb.Append(DocCommentFormatter.JsDoc(module.Doc));

        foreach (var service in module.Services)
        {
            sb.AppendLine(GenerateService(service));
            sb.AppendLine();
        }

        return sb.ToString();
    }

    // ═══════════════════════════════════════════════════════════════════
    // DOCUMENTATION HELPERS
    // ═══════════════════════════════════════════════════════════════════

    /// <summary>
    /// JSDoc block for a declaration, or "" when undocumented. Every line carries
    /// <paramref name="indent"/> and the block ends with a newline, so call sites
    /// <c>Append</c> it unconditionally.
    /// </summary>
    /// <param name="doc">Raw documentation text, or <c>null</c> when undocumented.</param>
    /// <param name="indent">Indent carried by every emitted line.</param>
    /// <param name="parameters">Parameters to emit a <c>@param</c> tag for.</param>
    /// <param name="attributes">
    /// The declaration's attributes. Only <c>@deprecated</c> is rendered, as a JSDoc
    /// <c>@deprecated</c> tag inside <em>this</em> block — TypeScript has no annotation a generated
    /// <c>interface</c> or <c>enum</c> could carry (decorators apply to classes and their members
    /// only, and would need a runtime import the generated client does not have), so the doc
    /// comment is the whole mechanism. Emitting it here rather than beside the declaration is what
    /// keeps a deprecated-but-undocumented declaration to one comment instead of two.
    /// </param>
    private static string Doc(string? doc, string indent = "", IReadOnlyList<DocParam>? parameters = null,
        IReadOnlyList<IonAttributeInstance>? attributes = null)
        => DocCommentFormatter.JsDoc(doc, indent, parameters, null,
            AttributeEmission.DeprecationOf(attributes) is { } deprecation
                ? AttributeEmission.JsDocDeprecated(deprecation)
                : null);

    /// <summary>
    /// JSDoc for a service method: summary plus one <c>@param</c> per documented argument.
    /// </summary>
    private static string MethodDoc(IonMethod method, string indent, Func<IonArgument, string>? nameOf = null)
    {
        nameOf ??= a => a.name.Identifier;
        var parameters = method.arguments.Select(a => new DocParam(nameOf(a), a.Doc)).ToList();
        return Doc(method.Doc, indent, parameters, method.attributes);
    }

    /// <summary>
    /// Adds an <c>@internal</c> tag to a method's JSDoc block, opening a block when the method is
    /// otherwise undocumented.
    /// </summary>
    /// <remarks>
    /// TypeScript cannot narrow the visibility of a member that an <c>implements</c> clause
    /// requires, so an <c>internal</c> method has to stay on the client class. <c>@internal</c> is
    /// the tag <c>tsc --stripInternal</c> keys on, so the method is dropped from the emitted
    /// <c>.d.ts</c> — which is the client surface a consumer actually programs against.
    /// </remarks>
    private static string InternalJsDoc(string methodDoc, string indent)
    {
        const string Tag = "@internal Not part of the client surface; for peer services only.";

        if (string.IsNullOrWhiteSpace(methodDoc))
            return $"{indent}/** {Tag} */\n";

        var close = $"{indent} */";
        var at = methodDoc.LastIndexOf(close, StringComparison.Ordinal);

        return at < 0
            ? methodDoc
            : string.Concat(methodDoc.AsSpan(0, at), $"{indent} * {Tag}\n", methodDoc.AsSpan(at));
    }

    private static string GenerateType(IonType type)
    {
        if (type is IonEnum enumType)
            return GenerateEnum(enumType);
        if (type is IonFlags flagsType)
            return GenerateFlags(flagsType);
        // Typedefs are tested before generic definitions: generics return null (skipped), so
        // checking IonGenericType first silently dropped every typedef.
        if (IsTypedefDeclaration(type))
            return GenerateTypedef(type);
        if (type is IonGenericType)
            return null;
        return GenerateMessage(type);
    }

    /// <summary>
    /// Whether <paramref name="type"/> is a typedef <em>declaration</em>.
    /// </summary>
    /// <remarks>
    /// <see cref="IonArray"/> inherits <c>isTypedef</c> from its element type, and every std
    /// builtin is declared with <c>isTypedef: true</c> (the fourth positional argument of the
    /// <c>new("u4", [...], [], true)</c> entries in <c>IonModule.GetStdModule</c>). The single
    /// <c>Value</c> field that <c>TransformStage.CompileTypedefs</c> emits is what tells a real
    /// alias apart from both.
    /// </remarks>
    private static bool IsTypedefDeclaration(IonType type)
        => type is { isTypedef: true, fields.Count: > 0 } and not IonArray and not IonUnresolvedType;

    private static string AppendPostfixForEnumType(IonType type, string constantValue)
    {
        if (type.name.Identifier.Equals("bigint"))
            return $"{constantValue}n as any";
        if (type.Bits >= 56)
            return $"{constantValue}n as any";
        return constantValue;
    }

    private static string GenerateEnum(IonEnum e)
    {
        var sb = new StringBuilder();
        sb.Append(Doc(e.Doc, attributes: e.attributes));
        sb.AppendLine($"export enum {e.name.Identifier}");
        sb.AppendLine("{");
        foreach (var m in e.members)
        {
            sb.Append(Doc(m.Doc, new string(' ', 2), attributes: m.attributes));
            sb.AppendLine(
                $"{new string(' ', 2)}{m.name.Identifier} = {AppendPostfixForEnumType(m.type, m.constantValue)},");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateFlags(IonFlags f)
    {
        var sb = new StringBuilder();
        sb.Append(Doc(f.Doc, attributes: f.attributes));
        sb.AppendLine($"export enum {f.name.Identifier}");
        sb.AppendLine("{");
        foreach (var m in f.members)
        {
            sb.Append(Doc(m.Doc, new string(' ', 2), attributes: m.attributes));
            sb.AppendLine(
                $"{new string(' ', 2)}{m.name.Identifier} = {AppendPostfixForEnumType(m.type, m.constantValue)},");
        }
        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Emits the alias declaration for a typedef. Purely nominal — the alias never reaches the
    /// wire, it exists so hand written TypeScript can name it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A scalar underlying type is spelled with its structural TypeScript type
    /// (<c>export type UserId = number;</c>) rather than the Ion name: the <c>u4</c> etc. aliases
    /// are <c>declare type</c>d in the bundle preamble and are not exported, so resolving them
    /// here keeps the exported alias meaningful to a consumer.
    /// </para>
    /// <para>
    /// Everything else falls back to <c>UnwrapType</c> — the same spelling fields use — so
    /// <c>typedef Ids = u4[]</c> becomes <c>IonArray&lt;u4&gt;</c> and <c>typedef Handle = Point</c>
    /// becomes <c>Point</c>.
    /// </para>
    /// </remarks>
    private static string GenerateTypedef(IonType type)
    {
        var field = type.fields.FirstOrDefault();
        var underlying = field is null
            ? "unknown"
            : ScalarTsNames.GetValueOrDefault(field.type.name.Identifier) ?? UnwrapType(field.type);

        return $"{Doc(type.Doc)}export type {type.name.Identifier} = {underlying};";
    }

    /// <summary>
    /// Ion scalar to its structural TypeScript type. Mirrors the <c>declare type</c> block the
    /// compile command writes at the head of the generated bundle.
    /// </summary>
    private static readonly Dictionary<string, string> ScalarTsNames = new(StringComparer.Ordinal)
    {
        ["bool"] = "boolean",
        ["i1"] = "number",
        ["i2"] = "number",
        ["i4"] = "number",
        ["i8"] = "bigint",
        ["i16"] = "bigint",
        ["u1"] = "number",
        ["u2"] = "number",
        ["u4"] = "number",
        ["u8"] = "bigint",
        ["u16"] = "bigint",
        ["f2"] = "number",
        ["f4"] = "number",
        ["f8"] = "number",
        ["string"] = "string"
    };

    private static string GenerateMessage(IonType type)
    {
        var sb = new StringBuilder();
        sb.Append(Doc(type.Doc, attributes: type.attributes));
        sb.AppendLine($"export interface {type.name.Identifier} {{");
        foreach (var typeField in type.fields)
        {
            sb.Append(Doc(typeField.Doc, new string(' ', 2), attributes: typeField.attributes));
            sb.AppendLine($"{new string(' ', 2)}{GenerateField(typeField)};");
        }

        sb.AppendLine("};");
        return sb.ToString();
    }

    private static string GenerateService(IonService service)
    {
        var sb = new StringBuilder();
        sb.Append(Doc(service.Doc, attributes: service.attributes));
        sb.AppendLine($"export interface I{service.name.Identifier} extends IIonService");
        sb.AppendLine("{");

        foreach (var method in service.methods)
        {
            var args = string.Join(", ", method.arguments.Select(GenerateArgument));
            sb.Append(MethodDoc(method, new string(' ', 2)));
            sb.AppendLine($"{new string(' ', 2)}{method.name.Identifier}({args}): {GenerateReturnType(method)};");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string GenerateField(IonField field) => $"{field.name.Identifier}: {UnwrapType(field.type)}";

    private static string GenerateArgument(IonArgument field)
    {
        if (field.mod is IonArgumentModifiers.Stream)
            return $"{field.name.Identifier}: AsyncIterable<{UnwrapType(field.type)}>";
        return $"{field.name.Identifier}: {UnwrapType(field.type)}";
    }

    private static string UnwrapType(IonType type) => (type, UseMaybeWrapper) switch
    {
        //IonUnresolvedType unresolved => throw new InvalidOperationException("Detected unresolved type"),
        (IonGenericType { IsMaybe: true } maybe, true) => $"IonMaybe<{UnwrapType(maybe.TypeArguments[0])}>",
        (IonGenericType { IsMaybe: true } maybe, false) => $"{UnwrapType(maybe.TypeArguments[0])} | null",
        // `T[]` and `T[N]` are both `IonArray<T>` (= `T[]`): TypeScript has no fixed-length array
        // type either, so N lives only in the formatter NAME — see UnwrapTypeForLookup.
        (IonGenericType { IsArray: true } array, _) => $"IonArray<{UnwrapType(array.TypeArguments[0])}>",
        // The platform `Map`/`Set`, which is what the runtime's readMap/readSet produce.
        (IonGenericType { IsMap: true } map, _) =>
            $"Map<{UnwrapType(map.TypeArguments[0])}, {UnwrapType(map.TypeArguments[1])}>",
        (IonGenericType { IsSet: true } set, _) => $"Set<{UnwrapType(set.TypeArguments[0])}>",
        // MUST be IonPartial, never the bare `Partial<T>`: TypeScript has a built-in utility
        // type of that name, so `Partial<Data>` type-checks and then throws
        // "Formatter not found" at runtime because nothing is registered under it.
        (IonGenericType { IsPartial: true } partial, _) => $"{PartialTypeName}<{UnwrapType(partial.TypeArguments[0])}>",
        (IonGenericType generic, _) => GenerateGenericTypeName(generic),
        _ => ResolveTypeName(type)
    };


    /// <summary><c>true</c> for <c>T[]?</c> — <c>Maybe&lt;Array&lt;T&gt;&gt;</c>.</summary>
    private static bool IsNullableArray(IonType type)
        => type is IonGenericType { IsMaybe: true } maybe
           && maybe.TypeArguments[0] is IonGenericType { IsArray: true };

    /// <summary><c>true</c> for <c>T[N]?</c> — <c>Maybe&lt;Array&lt;T, N&gt;&gt;</c>.</summary>
    private static bool IsNullableFixedArray(IonType type)
        => type is IonGenericType { IsMaybe: true } maybe
           && maybe.TypeArguments[0] is IonGenericType { IsArray: true, FixedSize: not null };

    /// <summary>
    /// The <em>registered formatter name</em> of a type. Diverges from <see cref="UnwrapType"/>
    /// wherever the wire shape carries information the TypeScript type cannot.
    /// </summary>
    /// <remarks>
    /// <c>T[N]</c> is the case that forces the split: its TypeScript type is the same
    /// <c>IonArray&lt;T&gt;</c> as an unsized array, so the declared length can only live in the
    /// lookup name — <c>f4[16]</c>, matching <c>IonFormatterStorage.registerFixedArray</c>. That
    /// also keeps <c>IonRequest.extractTypeName</c> honest: it strips only an <c>IonArray&lt;…&gt;</c>
    /// / <c>IonMaybe&lt;…&gt;</c> head, so <c>f4[16]</c> reaches <c>get()</c> intact and resolves to
    /// the length-checked formatter rather than to a plain <c>readArray</c>.
    /// </remarks>
    private static string UnwrapTypeForLookup(IonType type) => type switch
    {
        IonGenericType { IsMaybe: true } maybe => $"IonMaybe<{UnwrapTypeForLookup(maybe.TypeArguments[0])}>",
        IonGenericType { IsArray: true, FixedSize: { } size } fixedArray =>
            $"{UnwrapTypeForLookup(fixedArray.TypeArguments[0])}[{size}]",
        IonGenericType { IsArray: true } array => $"IonArray<{UnwrapTypeForLookup(array.TypeArguments[0])}>",
        IonGenericType { IsMap: true } map =>
            $"Map<{UnwrapTypeForLookup(map.TypeArguments[0])}, {UnwrapTypeForLookup(map.TypeArguments[1])}>",
        IonGenericType { IsSet: true } set => $"Set<{UnwrapTypeForLookup(set.TypeArguments[0])}>",
        IonGenericType { IsPartial: true } partial => $"{PartialTypeName}<{UnwrapTypeForLookup(partial.TypeArguments[0])}>",
        IonGenericType generic => GenerateGenericTypeName(generic),
        _ => ResolveTypeName(type)
    };

    /// <summary>
    /// The TypeScript spelling of <c>Partial&lt;T&gt;</c>. Exported from
    /// <c>ion.webcore.js</c> (as <c>IonPartial</c>/<c>IonPartialOf</c>) and used verbatim as the
    /// key <c>IonFormatterStorage.registerPartial</c> registers under, which is what makes
    /// <see cref="FormatterTemplateRef"/> resolve a partial with no special-casing.
    /// </summary>
    private const string PartialTypeName = "IonPartial";

    private static string GenerateGenericTypeName(IonGenericType generic)
        => $"{generic.name.Identifier}<{string.Join(',', generic.TypeArguments.Select(x => x.name.Identifier))}>";

    /// <summary>
    /// The name of a type when it appears as the <em>element</em> of a wrapper — both the TS type
    /// argument and the formatter lookup string in
    /// <c>IonFormatterStorage.readArray&lt;X&gt;(reader, 'X')</c>.
    /// </summary>
    private static string ResolveTypeName(IonType type)
    {
        if (type is IonUnion union)
            return $"I{union.name.Identifier}";
        // Without this, `Data~[]` emits readArray<Partial>(reader, 'Partial').
        if (type is IonGenericType { IsPartial: true } partial)
            return $"{PartialTypeName}<{UnwrapType(partial.TypeArguments[0])}>";
        // Same failure mode one wrapper out: a bare `Array` / `Maybe` / `Map` / `Set` is not a TS
        // type and is not a registered formatter key. Nothing reaches the Maybe arm today (every
        // caller peels the wrapper first), but falling through used to be how `T[]?` in return
        // position broke.
        //
        // UnwrapType, not UnwrapTypeForLookup: this result is used where a TypeScript *type* is
        // wanted. The two agree everywhere except `T[N]`, whose lookup name (`f4[16]`) is not a
        // type at all — see UnwrapTypeForLookup.
        if (type is IonGenericType { IsArray: true } or IonGenericType { IsMaybe: true }
            or IonGenericType { IsMap: true } or IonGenericType { IsSet: true })
            return UnwrapType(type);
        return type.name.Identifier;
    }

    private static string GenerateReturnType(IonMethod method)
    {
        if (method.returnType.IsVoid)
            return "Promise<void>";
        if (method.IsStreamable)
            return $"AsyncIterable<{UnwrapType(method.returnType)}>";
        return $"Promise<{UnwrapType(method.returnType)}>";
    }

    private string FormatterTemplate =>
        """
        IonFormatterStorage.register("{ionType}", {
          read(reader: CborReader): {ionType} {
            const arraySize = reader.readStartArray() ?? (() => { throw new Error("undefined len array not allowed") })();
            {fieldReadExpression}
            reader.readEndArrayAndSkip(arraySize - {fieldsCount});
            return { {ctorFields} };
          },
          write(writer: CborWriter, value: {ionType}): void {
            writer.writeStartArray({fieldsCount});
            {fieldWriteExpression}
            writer.writeEndArray();
          }
        });
        """;

    private string FormatterTemplateForUnion =>
        """
        IonFormatterStorage.register("{ionType}", {
          read(reader: CborReader): {ionType} {
            const arraySize = reader.readStartArray() ?? (() => { throw new Error("undefined len array not allowed") })();
            {fieldReadExpression}
            reader.readEndArrayAndSkip(arraySize - {fieldsCount});
            return new {ionType}({ctorFields});
          },
          write(writer: CborWriter, value: {ionType}): void {
            writer.writeStartArray({fieldsCount});
            {fieldWriteExpression}
            writer.writeEndArray();
          }
        });
        """;

    private static string FormatterTemplateRef(IonType type)
    {
        if (type.IsVoid)
            throw new InvalidOperationException();
        // The generic argument is the TypeScript type; the string is the registered formatter name.
        // Identical for every shape except `T[N]`, where the name carries the length the type
        // cannot (`get<IonArray<number>>('f4[16]')`).
        return $"IonFormatterStorage.get<{UnwrapType(type)}>('{UnwrapTypeForLookup(type)}')";
    }

    public string GenerateAllServiceClientImpl(IEnumerable<IonService> service)
    {
        var sb = new StringBuilder();

        sb.AppendLine(FileHeader());
        sb.AppendLine();

        foreach (var ionService in service)
        {
            sb.AppendLine(GenerateServiceClientImpl(ionService));
            sb.AppendLine();
        }

        return sb.ToCompiledString();
    }

    public string GenerateGlobalTypes()
    {
        throw new NotImplementedException();
    }


    public string GenerateAllFormatters(IEnumerable<IonType> types)
    {
        var candidates = types.Where(t => t is
                { IsBuiltin: false, IsScalar: false, IsVoid: false, IsUnionCase: false, IsUnion: false })
            // Typedefs are erased: `export type UserId = u4` is an alias with no distinct runtime
            // representation, so registering a formatter under its name would be dead code that
            // wraps the value in a 1-element CBOR array.
            .Where(t => !IsTypedefDeclaration(t))
            .ToArray();
        var sorted = TopoSortByDependencies(candidates);

        var sb = new StringBuilder();

        foreach (var t in sorted)
        {
            sb.AppendLine(GenerateFormatterForType(t));
            sb.AppendLine();
        }

        return sb.ToCompiledString();
    }

    // ═══════════════════════════════════════════════════════════════════
    // Partial<T> SCHEMA REGISTRATION
    // ═══════════════════════════════════════════════════════════════════

    /// <summary>
    /// Emits one <c>IonFormatterStorage.registerPartial</c> per message reached through a
    /// <c>Partial&lt;T&gt;</c> anywhere in the compilation, or <c>""</c> when there are none.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Registration name is the lookup name <see cref="UnwrapTypeForLookup"/> produces for the
    /// partial (<c>IonPartial&lt;Vector&gt;</c>), so the ordinary
    /// <see cref="FormatterTemplateRef"/> output resolves it with no special-casing.
    /// </para>
    /// <para>
    /// The array is in Ion declaration order, which is the order the encoder writes entries in —
    /// that is what keeps the bytes identical to the C# and Rust runtimes.
    /// </para>
    /// <para>
    /// The field formatters are looked up lazily (per read/write), so these calls may appear
    /// before the <c>register</c> calls of the types they mention.
    /// </para>
    /// </remarks>
    /// <summary>
    /// Every registration this compilation needs at module load: the parameterised container
    /// formatters first (<c>Map</c>, <c>Set</c>, <c>T[N]</c>, and a nested <c>T[]</c>), then one
    /// <c>registerPartial</c> per <c>Partial&lt;T&gt;</c> target.
    /// </summary>
    /// <remarks>
    /// The name is historical — it predates the containers — and is kept because it is the single
    /// hook the browser generation path calls. Both halves are order-insensitive: every registered
    /// formatter resolves the names it mentions lazily, on first read/write.
    /// </remarks>
    public string GeneratePartialRegistrations(IEnumerable<IonType> types, IEnumerable<IonService> services)
    {
        var typeList = types.ToList();
        var serviceList = services.ToList();

        return GenerateContainerRegistrations(typeList, serviceList)
               + GeneratePartialSchemaRegistrations(typeList, serviceList);
    }

    // ═══════════════════════════════════════════════════════════════════
    // Map<K,V> / Set<T> / T[N] REGISTRATION
    // ═══════════════════════════════════════════════════════════════════

    /// <summary>
    /// One named formatter per parameterised container the schema uses, or <c>""</c> when there
    /// are none.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Formatter lookup in this runtime is by <em>string name</em>, so a container has to be minted
    /// under a name before anything can nest it — inside a <c>Partial</c> schema, a <c>Map</c>
    /// value, a return type. <c>registerMap</c>/<c>registerSet</c>/<c>registerFixedArray</c> exist
    /// for exactly that; each takes the names of its parts, so the emission below is inside-out
    /// (post-order) purely for readability.
    /// </para>
    /// <para>
    /// The odd one out is a plain <c>T[]</c> nested in a container. Everywhere else an array is
    /// reached with its element type (<c>readArray(reader, 'User')</c>), so the runtime has no
    /// formatter registered for <c>IonArray&lt;T&gt;</c> itself and <c>Map&lt;string, User[]&gt;</c>
    /// would fail with "Formatter not found: IonArray&lt;User&gt;". It is registered here rather
    /// than in <c>ion.webcore.js</c> only because the generator cannot add it there — this mirrors
    /// the <c>Ion_nested_array_Formatter</c> the C# target emits for the same reason.
    /// </para>
    /// </remarks>
    private static string GenerateContainerRegistrations(
        IReadOnlyList<IonType> types, IReadOnlyList<IonService> services)
    {
        var emitted = new HashSet<string>(StringComparer.Ordinal);
        var lines = new List<string>();

        foreach (var type in types)
        {
            foreach (var field in type.fields)
                Visit(field.type, false);

            if (type is IonUnion union)
                foreach (var field in union.types.SelectMany(c => c.fields))
                    Visit(field.type, false);
        }

        foreach (var method in services.SelectMany(s => s.methods))
        {
            foreach (var argument in method.arguments)
                Visit(argument.type, false);
            Visit(method.returnType, false);
        }

        if (lines.Count == 0)
            return "";

        return string.Join("\n", lines) + "\n\n";

        void Visit(IonType type, bool insideContainer)
        {
            if (type is not IonGenericType generic)
                return;

            var childInsideContainer = insideContainer || generic.IsMap || generic.IsSet;

            // Post-order: an inner container's name must read before the outer one that mentions it.
            foreach (var argument in generic.TypeArguments)
                Visit(argument, childInsideContainer);

            var name = UnwrapTypeForLookup(generic);

            switch (generic)
            {
                case { IsMap: true }:
                {
                    if (!emitted.Add(name)) return;
                    var key = generic.TypeArguments[0];
                    var value = generic.TypeArguments[1];
                    lines.Add(
                        $"IonFormatterStorage.registerMap<{UnwrapType(key)}, {UnwrapType(value)}>(\"{name}\", \"{UnwrapTypeForLookup(key)}\", \"{UnwrapTypeForLookup(value)}\");");
                    return;
                }

                case { IsSet: true }:
                {
                    if (!emitted.Add(name)) return;
                    var element = generic.TypeArguments[0];
                    lines.Add(
                        $"IonFormatterStorage.registerSet<{UnwrapType(element)}>(\"{name}\", \"{UnwrapTypeForLookup(element)}\");");
                    return;
                }

                case { IsArray: true, FixedSize: { } size }:
                {
                    if (!emitted.Add(name)) return;
                    var element = generic.TypeArguments[0];
                    lines.Add(
                        $"IonFormatterStorage.registerFixedArray<{UnwrapType(element)}>(\"{name}\", \"{UnwrapTypeForLookup(element)}\", {size});");
                    return;
                }

                case { IsArray: true } when insideContainer:
                {
                    if (!emitted.Add(name)) return;
                    var element = generic.TypeArguments[0];
                    lines.Add(
                        $"IonFormatterStorage.register<{UnwrapType(generic)}>(\"{name}\", {{\n" +
                        $"  read: (reader) => IonFormatterStorage.readArray<{UnwrapType(element)}>(reader, \"{UnwrapTypeForLookup(element)}\"),\n" +
                        $"  write: (writer, value) => IonFormatterStorage.writeArray<{UnwrapType(element)}>(writer, value, \"{UnwrapTypeForLookup(element)}\"),\n" +
                        "});");
                    return;
                }
            }
        }
    }

    private string GeneratePartialSchemaRegistrations(IEnumerable<IonType> types, IEnumerable<IonService> services)
    {
        var targets = CollectPartialTargets(types.ToList(), services.ToList());
        if (targets.Count == 0)
            return "";

        var sb = new StringBuilder();

        foreach (var target in targets)
        {
            var name = UnwrapType(target);
            sb.AppendLine($"IonFormatterStorage.registerPartial<{name}>(\"{PartialTypeName}<{name}>\", [");
            foreach (var field in target.fields)
                sb.AppendLine($"  {PartialFieldDescriptor(field)},");
            sb.AppendLine("]);");
            sb.AppendLine();
        }

        return sb.ToString();
    }

    /// <summary>One <c>{ name, type, kind }</c> descriptor of a <c>Partial&lt;T&gt;</c> schema.</summary>
    /// <remarks>
    /// <c>type</c> is the <em>element</em> formatter name for the <c>array</c>/<c>maybe</c>/
    /// <c>nullable</c> kinds. <c>X[]?</c> is emitted as plain <c>array</c>: the codec decides
    /// null before the field codec ever runs (<c>null</c> ⇒ cleared, and "modified to null" is
    /// deliberately the same three bytes), so the field codec only ever sees a real array.
    /// </remarks>
    private static string PartialFieldDescriptor(IonField field)
    {
        var name = field.name.Identifier;

        switch (field.type)
        {
            // `X[N]` and `X[N]?` are plain values, not `kind: "array"`: the `array` kind reads an
            // unsized array with readArray, which would let a patch carry any length. The whole
            // fixed array is one registered formatter (`f4[16]`), and that formatter is what
            // enforces N. Same reason `X[]?` collapses to `array`: the codec decides null before
            // the field codec runs, so the field codec only ever sees a real array.
            case IonGenericType { IsArray: true, FixedSize: not null } fixedArray:
                return $"{{ name: \"{name}\", type: \"{UnwrapTypeForLookup(fixedArray)}\" }}";

            case IonGenericType { IsArray: true } array:
                return $"{{ name: \"{name}\", type: \"{UnwrapTypeForLookup(array.TypeArguments[0])}\", kind: \"array\" }}";

            case IonGenericType { IsMaybe: true } maybe:
            {
                var inner = maybe.TypeArguments[0];
                if (inner is IonGenericType { IsArray: true, FixedSize: not null } innerFixed)
                    return $"{{ name: \"{name}\", type: \"{UnwrapTypeForLookup(innerFixed)}\" }}";
                if (inner is IonGenericType { IsArray: true } innerArray)
                    return $"{{ name: \"{name}\", type: \"{UnwrapTypeForLookup(innerArray.TypeArguments[0])}\", kind: \"array\" }}";

                var kind = UseMaybeWrapper ? "maybe" : "nullable";
                return $"{{ name: \"{name}\", type: \"{UnwrapTypeForLookup(inner)}\", kind: \"{kind}\" }}";
            }

            // Includes Partial<X>, whose lookup name is IonPartial<X>.
            default:
                return $"{{ name: \"{name}\", type: \"{UnwrapTypeForLookup(field.type)}\" }}";
        }
    }

    /// <summary>Every message reached through a <c>Partial&lt;T&gt;</c>, in first-seen order.</summary>
    private static List<IonType> CollectPartialTargets(
        IReadOnlyList<IonType> types, IReadOnlyList<IonService> services)
    {
        var seen = new HashSet<string>(StringComparer.Ordinal);
        var targets = new List<IonType>();

        foreach (var type in types)
        {
            foreach (var field in type.fields)
                Visit(field.type);

            if (type is IonUnion union)
                foreach (var field in union.types.SelectMany(c => c.fields))
                    Visit(field.type);
        }

        foreach (var method in services.SelectMany(s => s.methods))
        {
            foreach (var argument in method.arguments)
                Visit(argument.type);
            Visit(method.returnType);
        }

        return targets;

        void Visit(IonType type)
        {
            if (type is not IonGenericType generic)
                return;

            if (generic is { IsPartial: true, TypeArguments.Count: > 0 })
            {
                // Resolve first: a `T~` reached only through a wrapper (`T~[]`, `T~?`,
                // `Map<K, T~>`) still carries an IonUnresolvedType here. See IonPartialTargets.
                var target = IonPartialTargets.Resolve(generic.TypeArguments[0], types);
                if (target is not null and not (IonEnum or IonFlags or IonUnion or IonUnresolvedType)
                    && seen.Add(UnwrapType(target)))
                    targets.Add(target);
            }

            foreach (var argument in generic.TypeArguments)
                Visit(argument);
        }
    }

    private static string GenerateFormatterForEnum(IonEnum @enum) =>
        """
            IonFormatterStorage.register("{ionType}", {
              read(reader: CborReader): {ionType} {
                const num = ({readEnumValue}.read(reader))
                return {ionType}[num] !== undefined ? num as {ionType} : (() => {throw new Error('invalid enum type')})();
              },
              write(writer: CborWriter, value: {ionType}): void {
                const casted: {baseTypeName} = value;
                {writeEnumValue}
              }
            });
            """
            .Replace("{ionType}", @enum.name.Identifier)
            .Replace("{baseTypeName}", @enum.baseType.name.Identifier)
            .Replace("{readEnumValue}", FormatterTemplateRef(@enum.baseType))
            .Replace("{writeEnumValue}", $"{FormatterTemplateRef(@enum.baseType)}.write(writer, casted);");

    private static string GenerateFormatterForFlags(IonFlags @enum) =>
        """
            IonFormatterStorage.register("{ionType}", {
              read(reader: CborReader): {ionType} {
                const num = ({readEnumValue}.read(reader))
                return num as any;
              },
              write(writer: CborWriter, value: {ionType}): void {
                const casted: {baseTypeName} = value as any;
                {writeEnumValue}
              }
            });
            """
            .Replace("{ionType}", @enum.name.Identifier)
            .Replace("{baseTypeName}", @enum.baseType.name.Identifier)
            .Replace("{readEnumValue}", FormatterTemplateRef(@enum.baseType))
            .Replace("{writeEnumValue}", $"{FormatterTemplateRef(@enum.baseType)}.write(writer, casted);");


    private string GenerateFormatterForType(IonType type)
    {
        if (type is IonEnum @enum)
            return GenerateFormatterForEnum(@enum);
        if (type is IonFlags flags)
            return GenerateFormatterForFlags(flags);

        var name = type.name.Identifier;

        var template = (type.IsUnionCase ? FormatterTemplateForUnion : FormatterTemplate)
            .Replace("{ionType}", name)
            .Replace("{fieldReadExpression}", GenerateReadField(type))
            .Replace("{ctorFields}", GenerateCaptureField(type))
            .Replace("{fieldWriteExpression}", GenerateWriteField(type))
            .Replace("{fieldsCount}", type.fields.Count.ToString());

        return template;
    }

    private static string GenerateCaptureField(IonType type)
        => string.Join(", ", type.fields.Select(x => $"{x.name.Identifier}"));

    private static string GenerateCaptureField(IonMethod method)
        => string.Join(", ", method.arguments.Select(x => $"{x.name.Identifier}"));

    private static string GenerateReadField(IonType type) =>
        string.Join($"\n{new string(' ', 4)}", type.fields.Select(GenerateReadField));

    private static string GenerateReadField(IonField field) =>
        field switch
        {
            { type: { IsArray: true } } => GenerateReadArrayField(field),
            { type: { IsMaybe: true } } => GenerateReadMaybeField(field),
            { type: { IsPartial: true } } => GenerateReadPartialField(field),
            _ => $"const {field.name.Identifier} = {FormatterTemplateRef(field.type)}.read(reader);"
        };

    private static string GenerateReadArgument(IonArgument argument) =>
        argument switch
        {
            { type: { IsArray: true } } => GenerateReadArrayField(argument),
            { type: { IsMaybe: true } } => GenerateReadMaybeField(argument),
            { type: { IsPartial: true } } => GenerateReadPartialField(argument),
            _ =>
                $"const {argument.name.Identifier} = {FormatterTemplateRef(argument.type)}.read(reader);"
        };


    private static string GenerateWriteArgument(IonArgument argument) =>
        argument switch
        {
            { type: { IsArray: true } } => GenerateWriteArrayField(argument),
            { type: { IsMaybe: true } } => GenerateWriteMaybeField(argument),
            { type: { IsPartial: true } } => GenerateWritePartialField(argument),
            _ =>
                $"{FormatterTemplateRef(argument.type)}.write(writer, {argument.name.Identifier});"
        };

    // ═══════════════════════════════════════════════════════════════════
    // Partial<T>  ("T~")
    // ═══════════════════════════════════════════════════════════════════
    //
    // A patch is a single value: the formatter registered by
    // IonFormatterStorage.registerPartial("IonPartial<T>", …) writes the whole CBOR map.
    // Nothing here is partial-specific beyond the lookup name, which UnwrapType already
    // spells IonPartial<T> — the point of these arms is that the name can never silently
    // become TypeScript's built-in `Partial<T>`.
    //
    // `Data~[]` / `Data~?` never reach these: Partial is the innermost wrapper, so those
    // are array/maybe shapes whose element type is Partial<Data>.

    private static string GenerateReadPartialField(ITypeWithName field)
        => $"const {field.Name.Identifier} = {FormatterTemplateRef(field.Type)}.read(reader);";

    private static string GenerateWritePartialField(ITypeWithName field)
        => $"{FormatterTemplateRef(field.Type)}.write(writer, {field.Name.Identifier});";

    /// <summary>
    /// <c>Fixed</c> for a <c>T[N]</c>, <c>""</c> for an unsized <c>T[]</c> — the infix that selects
    /// the length-checked <c>readFixedArray</c> / <c>writeFixedArray</c> family.
    /// </summary>
    private static string FixedInfix(IonGenericType array) => array.FixedSize is null ? "" : "Fixed";

    /// <summary>The trailing <c>, N</c> argument of a fixed-size array call, or <c>""</c>.</summary>
    private static string FixedLengthArg(IonGenericType array)
        => array.FixedSize is { } size ? $", {size}" : "";

    private static string GenerateReadArrayField(ITypeWithName field)
    {
        if (field.Type is not IonGenericType { IsArray: true } arrayType)
            throw new InvalidOperationException();
        var element = arrayType.TypeArguments[0];
        return
            $"const {field.Name.Identifier} = IonFormatterStorage.read{FixedInfix(arrayType)}Array<{ResolveTypeName(element)}>(reader, '{UnwrapTypeForLookup(element)}'{FixedLengthArg(arrayType)});";
    }

    private static string GenerateReadMaybeField(ITypeWithName field)
    {
        if (field.Type is not IonGenericType { IsMaybe: true } maybeType)
            throw new InvalidOperationException();
        if (maybeType.TypeArguments[0] is IonGenericType { IsArray: true } innerArray)
        {
            var element = innerArray.TypeArguments[0];
            return
                $"const {field.Name.Identifier} = IonFormatterStorage.readNullable{FixedInfix(innerArray)}Array<{ResolveTypeName(element)}>(reader, '{UnwrapTypeForLookup(element)}'{FixedLengthArg(innerArray)});";
        }
        return
            $"const {field.Name.Identifier} = IonFormatterStorage.{(UseMaybeWrapper ? "readMaybe" : "readNullable")}<{ResolveTypeName(maybeType.TypeArguments[0])}>(reader, '{UnwrapTypeForLookup(maybeType.TypeArguments[0])}');";
    }


    private static string GenerateWriteArrayField(ITypeWithName field)
    {
        if (field.Type is not IonGenericType { IsArray: true } arrayType)
            throw new InvalidOperationException();
        var element = arrayType.TypeArguments[0];
        return
            $"IonFormatterStorage.write{FixedInfix(arrayType)}Array<{ResolveTypeName(element)}>(writer, {field.Name.Identifier}, '{UnwrapTypeForLookup(element)}'{FixedLengthArg(arrayType)});";
    }

    private static string GenerateWriteMaybeField(ITypeWithName field)
    {
        if (field.Type is not IonGenericType { IsMaybe: true } maybeType)
            throw new InvalidOperationException();
        if (maybeType.TypeArguments[0] is IonGenericType { IsArray: true } innerArray)
        {
            var element = innerArray.TypeArguments[0];
            return
                $"IonFormatterStorage.writeNullable{FixedInfix(innerArray)}Array<{ResolveTypeName(element)}>(writer, {field.Name.Identifier}, '{UnwrapTypeForLookup(element)}'{FixedLengthArg(innerArray)});";
        }
        return
            $"IonFormatterStorage.{(UseMaybeWrapper ? "writeMaybe" : "writeNullable")}<{ResolveTypeName(maybeType.TypeArguments[0])}>(writer, {field.Name.Identifier}, '{UnwrapTypeForLookup(maybeType.TypeArguments[0])}');";
    }

    private static string GenerateWriteReturnValue(IonType returnType) =>
        returnType switch
        {
            { IsArray: true } => GenerateWriteReturnValueForArray(returnType),
            { IsMaybe: true } => GenerateWriteReturnValueForMaybe(returnType),
            // Partial<T> falls through: FormatterTemplateRef resolves it to
            // IonFormatterStorage.get<IonPartial<T>>('IonPartial<T>'), which is exactly right.
            _ => $"{FormatterTemplateRef(returnType)}.write(writer, result);"
        };

    private static string GenerateWriteReturnValueForArray(IonType returnType)
    {
        if (returnType is not IonGenericType { IsArray: true } arrayType)
            throw new InvalidOperationException();
        var element = arrayType.TypeArguments[0];
        if (arrayType.FixedSize is { } size)
            return
                $"IonFormatterStorage.writeFixedArray<{ResolveTypeName(element)}>(writer, result, '{UnwrapTypeForLookup(element)}', {size});";
        return
            $"{FormatterTemplateRef(element)}.writeArray(writer, result, '{FormatterTemplateRef(element)}');";
    }

    private static string GenerateWriteReturnValueForMaybe(IonType returnType)
    {
        if (returnType is not IonGenericType { IsMaybe: true } maybeType)
            throw new InvalidOperationException();
        if (maybeType.TypeArguments.First() is IonGenericType { IsArray: true } innerArray)
        {
            var element = innerArray.TypeArguments[0];
            return
                $"IonFormatterStorage.writeNullable{FixedInfix(innerArray)}Array<{ResolveTypeName(element)}>(writer, result, '{UnwrapTypeForLookup(element)}'{FixedLengthArg(innerArray)});";
        }
        return
            $"{FormatterTemplateRef(maybeType.TypeArguments.First())}.{(UseMaybeWrapper ? "writeMaybe" : "writeNullable")}(writer, result, '{FormatterTemplateRef(maybeType.TypeArguments.First())}');";
    }

    private static string GenerateWriteField(IonType type)
        => string.Join($"\n{new string(' ', 4)}", type.fields.Select(GenerateWriteField));

    private static string GenerateWriteField(IonField field)
    {
        return field switch
        {
            { type: { IsArray: true } } => GenerateWriteArrayField(field),
            { type: { IsMaybe: true } } => GenerateWriteMaybeField(field),
            // Partial<T> falls through — see GenerateWriteReturnValue.
            _ => $"{FormatterTemplateRef(field.type)}.write(writer, value.{field.name.Identifier});"
        };
    }

    private static string GenerateReadArguments(IonMethod method)
        => string.Join($"\n{new string(' ', 4)}", method.arguments.Select(GenerateReadArgument));

    private static string GenerateWriteArguments(IonMethod method)
        => string.Join($"\n{new string(' ', 4)}",
            method.arguments.Where(x => x.mod is not IonArgumentModifiers.Stream).Select(GenerateWriteArgument));

    private static string GenerateWriteArrayField(IonField field)
    {
        if (field.type is not IonGenericType { IsArray: true } arrayType)
            throw new InvalidOperationException();
        var element = arrayType.TypeArguments[0];
        return
            $"IonFormatterStorage.write{FixedInfix(arrayType)}Array<{ResolveTypeName(element)}>(writer, value.{field.name.Identifier}, '{UnwrapTypeForLookup(element)}'{FixedLengthArg(arrayType)});";
    }

    private static string GenerateWriteMaybeField(IonField field)
    {
        if (field.type is not IonGenericType { IsMaybe: true } maybeType)
            throw new InvalidOperationException();
        if (maybeType.TypeArguments[0] is IonGenericType { IsArray: true } innerArray)
        {
            var element = innerArray.TypeArguments[0];
            return
                $"IonFormatterStorage.writeNullable{FixedInfix(innerArray)}Array<{ResolveTypeName(element)}>(writer, value.{field.name.Identifier}, '{UnwrapTypeForLookup(element)}'{FixedLengthArg(innerArray)});";
        }
        return
            $"IonFormatterStorage.{(UseMaybeWrapper ? "writeMaybe" : "writeNullable")}<{ResolveTypeName(maybeType.TypeArguments[0])}>(writer, value.{field.name.Identifier}, '{UnwrapTypeForLookup(maybeType.TypeArguments[0])}');";
    }

    private static IReadOnlyList<IonType> TopoSortByDependencies(IReadOnlyList<IonType> types)
    {
        var byName = types.ToDictionary(t => t.name.Identifier, t => t);
        var visited = new HashSet<string>();
        var temp = new HashSet<string>();
        var result = new List<IonType>();

        foreach (var t in types) Visit(t);
        return result;

        void Visit(IonType t)
        {
            var key = t.name.Identifier;
            if (visited.Contains(key)) return;
            if (!temp.Add(key)) return;

            foreach (var f in t.fields ?? [])
            {
                var ft = f.type;
                if (ft is null || ft.IsBuiltin || ft.IsScalar || ft.IsVoid) continue;
                if (byName.TryGetValue(ft.name.Identifier, out var dep))
                    Visit(dep);
            }

            temp.Remove(key);
            visited.Add(key);
            result.Add(t);
        }
    }


    private static readonly string ServiceClientImplTemplate =
        """
        {serviceDoc}export class {serviceTypename}_Executor extends ServiceExecutor<I{serviceTypename}> implements I{serviceTypename} {
          constructor(public ctx: IonClientContext, private signal: AbortSignal) {
              super();
          }

          {body}
        }

        IonFormatterStorage.registerClientExecutor<I{serviceTypename}>('{serviceTypename}', {serviceTypename}_Executor);
        """;

    private static readonly string ServiceClientMethodDecl =
        """
        {methodDoc}  async {methodName}({args}): Promise<{methodReturnType}> {
            const req = new IonRequest(this.ctx, "I{serviceTypename}", "{methodName}");
                  
            const writer = new CborWriter();
              
            writer.writeStartArray({argSize});
                  
            {argsWrite}
              
            writer.writeEndArray();
                  
            return await req.callAsyncT<{methodReturnType}>("{methodReturnTypeLookup}", writer.data, this.signal);
          }
        """;

    private static readonly string ServiceClientMethodDeclNullable =
        """
        {methodDoc}  async {methodName}({args}): Promise<{methodReturnType}> {
            const req = new IonRequest(this.ctx, "I{serviceTypename}", "{methodName}");
                  
            const writer = new CborWriter();
              
            writer.writeStartArray({argSize});
                  
            {argsWrite}
              
            writer.writeEndArray();
                  
            return await req.callAsyncNullableT<{methodReturnTypeInner}>("{methodReturnTypeInner}", writer.data, this.signal);
          }
        """;

    /// <summary>
    /// <c>T[]?</c> — <c>Maybe&lt;Array&lt;T&gt;&gt;</c>.
    /// </summary>
    /// <remarks>
    /// This shape used to reuse <see cref="ServiceClientMethodDeclNullable"/>, which is wrong twice
    /// over: <c>callAsyncNullableT&lt;T&gt;</c> is typed <c>Promise&lt;T | null&gt;</c> against a
    /// declared <c>Promise&lt;IonArray&lt;T&gt; | null&gt;</c> (a type error), and at runtime it
    /// decodes one element instead of the array. <c>callAsyncNullableArrayT</c> is the
    /// transport-side counterpart of the <c>X[]?</c> field path's
    /// <c>IonFormatterStorage.readNullableArray</c>.
    /// </remarks>
    private static readonly string ServiceClientMethodDeclNullableArray =
        """
        {methodDoc}  async {methodName}({args}): Promise<{methodReturnType}> {
            const req = new IonRequest(this.ctx, "I{serviceTypename}", "{methodName}");

            const writer = new CborWriter();

            writer.writeStartArray({argSize});

            {argsWrite}

            writer.writeEndArray();

            return await req.callAsyncNullableArrayT<{methodReturnTypeInner}>("{methodReturnTypeInner}", writer.data, this.signal);
          }
        """;

    /// <summary>
    /// <c>T[N]?</c> — <c>Maybe&lt;Array&lt;T, N&gt;&gt;</c>.
    /// </summary>
    /// <remarks>
    /// Neither array neighbour fits. <see cref="ServiceClientMethodDeclNullableArray"/> calls
    /// <c>callAsyncNullableArrayT</c>, which is <c>readNullableArray</c> over the <em>element</em>
    /// name and therefore accepts any length — the one thing <c>T[N]</c> exists to reject. The
    /// whole fixed array is a single registered formatter instead (<c>f4[16]</c>), so the plain
    /// nullable call resolves it and the length check happens inside it. That is also why the type
    /// and the lookup name are two placeholders here: <c>f4[16]</c> is a formatter name, not a
    /// TypeScript type.
    /// <para>
    /// The non-nullable <c>T[N]</c> needs no template of its own —
    /// <see cref="ServiceClientMethodDecl"/> already keeps the two apart as
    /// <c>{methodReturnType}</c> and <c>{methodReturnTypeLookup}</c>.
    /// </para>
    /// </remarks>
    private static readonly string ServiceClientMethodDeclNullableFixedArray =
        """
        {methodDoc}  async {methodName}({args}): Promise<{methodReturnType}> {
            const req = new IonRequest(this.ctx, "I{serviceTypename}", "{methodName}");

            const writer = new CborWriter();

            writer.writeStartArray({argSize});

            {argsWrite}

            writer.writeEndArray();

            return await req.callAsyncNullableT<{methodReturnTypeInner}>("{methodReturnTypeInnerLookup}", writer.data, this.signal);
          }
        """;

    private static readonly string ServiceClientMethodDeclNoReturn =
        """
        {methodDoc}  async {methodName}({args}): Promise<void> {
            const req = new IonRequest(this.ctx, "I{serviceTypename}", "{methodName}");
                  
            const writer = new CborWriter();
              
            writer.writeStartArray({argSize});
                  
            {argsWrite}
              
            writer.writeEndArray();
                  
            await req.callAsync(writer.data, this.signal);
          }
        """;

    private static readonly string ServiceClientMethodDeclStream =
        """
        {methodDoc}  {methodName}({args}): AsyncIterable<{methodReturnType}> {
            const ws = new IonWsClient(this.ctx, "I{serviceTypename}", "{methodName}");
            
            const writer = new CborWriter();
            
            writer.writeStartArray({argSize});
            
            {argsWrite}
            
            writer.writeEndArray();
            
            return {streamReturnTemplate};
          }
        """;

    private string GenerateServiceClientImpl(IonService service)
    {
        var methodsBuilder = new StringBuilder();
        var methodInfoDecl = new StringBuilder();
        var serviceTypename = service.name.Identifier;
        var builder = ServiceClientImplTemplate;

        methodInfoDecl.AppendLine();
        methodsBuilder.AppendLine();

        foreach (var method in service.methods)
        {
            var methodName = method.name.Identifier;
            var argSize = method.arguments.Count(x => x.mod is not IonArgumentModifiers.Stream);

            var writeArgsExpression = GenerateWriteArguments(method);

            var methodArgs = string.Join(", ", method.arguments.Select(GenerateClientMethodArgument));

            var inputStreamType = method.arguments.FirstOrDefault(x => x.mod is IonArgumentModifiers.Stream);

            var template =
                method.IsStreamable
                    ? ServiceClientMethodDeclStream
                    : method.returnType.IsVoid
                        ? ServiceClientMethodDeclNoReturn
                        // Before IsNullableArray, which `T[N]?` also answers: taking the unsized
                        // branch would drop the length check silently rather than fail to compile.
                        : IsNullableFixedArray(method.returnType)
                            ? ServiceClientMethodDeclNullableFixedArray
                            : IsNullableArray(method.returnType)
                                ? ServiceClientMethodDeclNullableArray
                                : method.returnType.IsMaybe
                                    ? ServiceClientMethodDeclNullable
                                    : ServiceClientMethodDecl;

            if (inputStreamType is not null)
                template = template.Replace("{streamReturnTemplate}",
                    $"ws.callServerStreamingFullDuplex<{{methodReturnType}}, {UnwrapType(inputStreamType.Type)}>(\"{{methodReturnTypeLookup}}\", writer.data, inputStream, \"{UnwrapType(inputStreamType.Type)}\", this.signal)");
            else
                template = template.Replace("{streamReturnTemplate}",
                    "ws.callServerStreaming<{methodReturnType}>(\"{methodReturnTypeLookup}\", writer.data, this.signal)");

            // TypeScript cannot narrow the visibility of a member the `implements I{Service}`
            // clause requires, so an internal method stays on the class and is marked `@internal`
            // instead: `tsc --stripInternal` drops it from the emitted .d.ts, which is the
            // published client surface.
            var methodDoc = MethodDoc(method, new string(' ', 2), ClientArgumentDocName);
            if (method.IsInternal())
                methodDoc = InternalJsDoc(methodDoc, new string(' ', 2));

            var templateMethod =
                template
                    .Replace("{methodDoc}", methodDoc)
                    .Replace("{serviceTypename}", serviceTypename)
                    .Replace("{methodName}", methodName)
                    .Replace("{argSize}", argSize.ToString())
                    .Replace("{argsWrite}", writeArgsExpression)
                    .Replace("{args}", methodArgs);

            if (!method.returnType.IsVoid)
            {
                templateMethod = templateMethod
                    .Replace("{methodReturnType}", UnwrapType(method.returnType))
                    .Replace("{methodReturnTypeLookup}", UnwrapTypeForLookup(method.returnType));

                // For nullable return types, set inner type
                if (method.returnType is IonGenericType { IsMaybe: true } maybeRet)
                {
                    var innerType = maybeRet.TypeArguments[0];

                    // `T[N]?` keeps the WHOLE array as the transport's unit — the fixed formatter
                    // is registered under one name and is what checks the length — while `T[]?`
                    // hands callAsyncNullableArrayT the element, which is what readNullableArray
                    // wants. Peeling in the fixed case would reinstate the unsized read.
                    var (innerTypeName, innerLookupName) = innerType switch
                    {
                        IonGenericType { IsArray: true, FixedSize: not null } innerFixed =>
                            (UnwrapType(innerFixed), UnwrapTypeForLookup(innerFixed)),
                        IonGenericType { IsArray: true } innerArr =>
                            (UnwrapType(innerArr.TypeArguments[0]), UnwrapTypeForLookup(innerArr.TypeArguments[0])),
                        _ => (UnwrapType(innerType), UnwrapTypeForLookup(innerType))
                    };

                    templateMethod = templateMethod
                        .Replace("{methodReturnTypeInnerLookup}", innerLookupName)
                        .Replace("{methodReturnTypeInner}", innerTypeName);
                }
            }


            methodsBuilder.AppendLine(templateMethod);
        }

        return builder
            .Replace("{serviceDoc}", Doc(service.Doc, attributes: service.attributes))
            .Replace("{MethodInfoDecls}", methodInfoDecl.ToString())
            .Replace("{body}", methodsBuilder.ToString())
            .Replace("{serviceTypename}", serviceTypename);

        static string GenerateClientMethodArgument(IonArgument field)
        {
            if (field.mod is IonArgumentModifiers.Stream)
                return $"inputStream: AsyncIterable<{UnwrapType(field.type)}>";
            return $"{field.name.Identifier}: {UnwrapType(field.type)}";
        }
    }

    /// <summary>
    /// The generated client executor renames the streaming argument to <c>inputStream</c>;
    /// <c>@param</c> names must match the emitted signature.
    /// </summary>
    private static string ClientArgumentDocName(IonArgument arg)
        => arg.mod is IonArgumentModifiers.Stream ? "inputStream" : arg.name.Identifier;

    private string UnwrapUnionName(IonUnion union, IonType caseType)
    {
        return caseType.name.Identifier;
        // TODO
        return $"U{union.name.Identifier}_{caseType.name.Identifier}";
    }

    private string GenerateUnion(IonUnion union)
    {
        var builder = new StringBuilder();
        var checkBuilder = new StringBuilder();
        var absBuilder = new StringBuilder();

        checkBuilder.AppendLine();
        foreach (var unionCase in union.types)
        {
            checkBuilder.AppendLine(Union_InterfaceCheck
                .Replace("{normalizedCaseTypeName}", UnwrapUnionName(union, unionCase))
                .Replace("{caseTypeName}", unionCase.name.Identifier)
            );
        }

        foreach (var field in union.sharedFields)
        {
            absBuilder.Append(Doc(field.Doc, new string(' ', 2)));
            absBuilder.AppendLine($"  abstract {field.Name.Identifier}: {UnwrapType(field.type)};");
        }

        var unionInterface =
            Union_InterfaceBody
                .Replace("{unionDoc}", Doc(union.Doc, attributes: union.attributes))
                .Replace("{unionName}", union.name.Identifier)
                .Replace("{checks}", checkBuilder.ToString())
                .Replace("{abstractSharedFields}", absBuilder.ToString());


        builder.AppendLine();
        builder.AppendLine(unionInterface);


        var cases = GenerateUnionCase(union, out var targetTypesForFormatterGeneration);

        builder.AppendLine();
        builder.AppendLine(cases);

        builder.AppendLine();
        builder.AppendLine(GenerateUnionFormatterFraction(union));

        foreach (var ionType in targetTypesForFormatterGeneration)
        {
            //builder.AppendLine();
            //builder.AppendLine(GenerateMessage(ionType));
            builder.AppendLine();
            builder.AppendLine(GenerateFormatterForType(ionType));
        }

        return builder.ToString();
    }

    private string GenerateUnionCase(IonUnion union, out List<IonType> unionTypesRequiredFormatters)
    {
        unionTypesRequiredFormatters = new();
        var builder = new StringBuilder();
        var index = 0;
        foreach (var type in union.types)
        {
            if (!type.IsUnionCase)
            {
                index++;
                continue;
            }

            unionTypesRequiredFormatters.Add(type);

            var fields = string.Join(", ", type.fields.Select(f => $"public {GenerateField(f)}"));
            builder.AppendLine();
            builder.AppendLine(Union_CaseBody
                .Replace("{caseDoc}",
                    Doc(type.Doc, "", type.fields.Select(f => new DocParam(f.name.Identifier, f.Doc)).ToList(), type.attributes))
                .Replace("{fields}", fields.ToString())
                .Replace("{caseTypeName}", type.name.Identifier)
                .Replace("{unionName}", union.name.Identifier)
                .Replace("{caseIndex}", index.ToString())
            );

            index++;
        }

        return builder.ToString();
    }

    private static readonly string Union_InterfaceBody =
        """
        {unionDoc}export abstract class I{unionName} implements IIonUnion<I{unionName}>
        {
          abstract UnionKey: string;
          abstract UnionIndex: number;
          
          {abstractSharedFields}
          
          {checks}
        }
        """;

    private static readonly string Union_CaseBody =
        """
        {caseDoc}export class {caseTypeName} extends I{unionName}
        {
          constructor({fields}) { super(); }

          UnionKey: string = "{caseTypeName}";
          UnionIndex: number = {caseIndex};
        }
        """;

    private static readonly string Union_InterfaceCheck =
        """
          public is{caseTypeName}(): this is {normalizedCaseTypeName} {
            return this.UnionKey === "{normalizedCaseTypeName}";
          }
        """;

    private string GenerateUnionFormatterFraction(IonUnion union)
    {
        var builder = new StringBuilder();

        var writeChecks = new StringBuilder();
        var readChecks = new StringBuilder();
        var index = 0;
        foreach (var @case in union.types)
        {
            writeChecks.AppendLine(
                UnionWriteCheck
                    .Replace("{caseTypeName}", @case.name.Identifier)
                    .Replace("{caseIndex}", index.ToString())
            );
            readChecks.AppendLine(
                UnionReadCheck
                    .Replace("{caseTypeName}", @case.name.Identifier)
                    .Replace("{caseIndex}", index.ToString())
            );

            index++;
        }


        builder.AppendLine();
        builder.AppendLine(Union_InterfaceFormatter
            .Replace("{unionInterface}", union.name.Identifier)
            .Replace("{readCheks}", readChecks.ToString())
            .Replace("{writeChecks}", writeChecks.ToString())
        );

        return builder.ToString();
    }


    private static string Union_InterfaceFormatter =>
        """
        IonFormatterStorage.register("I{unionInterface}", {
          read(reader: CborReader): I{unionInterface} {
            reader.readStartArray();
            let value: I{unionInterface} = null as any;
            const unionIndex = reader.readUInt32();
            
            if (false)
            {}
            {readCheks}
            else throw new Error();
          
            reader.readEndArray();
            return value!;
          },
          write(writer: CborWriter, value: I{unionInterface}): void {
            writer.writeStartArray(2);
            writer.writeUInt32(value.UnionIndex);
            if (false)
            {}
            {writeChecks}  
            else throw new Error();
            writer.writeEndArray();
          }
        });
        """;

    private static readonly string UnionReadCheck =
        """
            else if (unionIndex == {caseIndex})
              value = IonFormatterStorage.get<{caseTypeName}>("{caseTypeName}").read(reader);
        """;

    private static readonly string UnionWriteCheck =
        """
            else if (value.UnionIndex == {caseIndex}) {
                IonFormatterStorage.get<{caseTypeName}>("{caseTypeName}").write(writer, value as {caseTypeName});
            }
        """;


    public string GenerateClientProxy(List<IonService> services)
    {
        var kvBuilder = new StringBuilder();
        var propsBuilder = new StringBuilder();
        // {kv} ServerInteraction: IServerInteraction;
        // {props} if (propKey === "ServerInteraction") return IonFormatterStorage.createExecutor("ServerInteraction", ctx, new AbortSignal());

        foreach (var service in services)
        {
            var srvName = service.name.Identifier;
            kvBuilder.AppendLine($"    {srvName}: I{srvName};");
            propsBuilder
                .AppendLine($"        if (propKey === \"{srvName}\") " +
                            $"return IonFormatterStorage.createExecutor(\"{srvName}\", ctx, controller.signal);");
        }

        return ProxyTemplate
            .Replace("{kv}", kvBuilder.ToString())
            .Replace("{props}", propsBuilder.ToString());
    }

    private static readonly string ProxyTemplate =
        """
        export function createClient(endpoint: string, interceptors: IonInterceptor[]) {
          const ctx = {
            baseUrl: endpoint,
            interceptors: interceptors
          } as IonClientContext;
          const controller = new AbortController();

          return new Proxy(
            {},
            {
              get(_target, propKey) {
                if (typeof propKey !== "string") return undefined;
        {props}

                throw new Error(`${propKey} service is not defined`);
              },
            }
          ) as {
        {kv}
          };
        }
        """;
}