//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace TestContracts;

/// <summary>
/// Round-trip surface for `datetime` and `decimal`.
///
/// The service level operand is itself a `datetime`, so every generated method signature
/// carries one — that is the position that would have gone unnoticed if only fields were
/// covered.
/// </summary>
public sealed class Ion_LedgerInteraction_ServiceExecutor(AsyncServiceScope scope) : IServiceExecutorRouter
{
    
    /// <summary>
    /// `datetime` in both argument and return position. The one method whose result proves
    /// the offset and the sub-millisecond tick survived the wire.
    /// </summary>
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task Echo_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<ILedgerInteraction>();
    
        const int argumentSize = 2;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __openedat = IonFormatterStorage<datetime>.Read(reader);
        var __at = IonFormatterStorage<datetime>.Read(reader);
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.Echo(__openedat, __at);
        
        IonFormatterStorage<datetime>.Write(writer, result);
    }
    /// <summary>
    /// `decimal` in both argument and return position.
    /// </summary>
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task EchoAmount_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<ILedgerInteraction>();
    
        const int argumentSize = 2;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __openedat = IonFormatterStorage<datetime>.Read(reader);
        var __amount = IonFormatterStorage<decimal>.Read(reader);
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.EchoAmount(__openedat, __amount);
        
        IonFormatterStorage<decimal>.Write(writer, result);
    }
    /// <summary>
    /// The whole message, so every field shape above goes over a real transport.
    /// </summary>
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task Roundtrip_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<ILedgerInteraction>();
    
        const int argumentSize = 2;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __openedat = IonFormatterStorage<datetime>.Read(reader);
        var __entry = IonFormatterStorage<LedgerEntry>.Read(reader);
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.Roundtrip(__openedat, __entry);
        
        IonFormatterStorage<LedgerEntry>.Write(writer, result);
    }
    /// <summary>
    /// Optional in argument and return position: `Maybe&lt;datetime&gt;` / `Maybe&lt;decimal&gt;`.
    /// A null `amount` returns null, so the null branch is reachable.
    /// </summary>
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task EchoMaybe_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<ILedgerInteraction>();
    
        const int argumentSize = 3;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __openedat = IonFormatterStorage<datetime>.Read(reader);
        var __at = reader.ReadNullable<datetime>();
        var __amount = reader.ReadNullable<decimal>();
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.EchoMaybe(__openedat, __at, __amount);
        
        IonFormatterStorage<decimal>.WriteNullable(writer, result);
    }
    /// <summary>
    /// Arrays of both, with an array return.
    /// </summary>
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task EchoMany_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<ILedgerInteraction>();
    
        const int argumentSize = 3;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __openedat = IonFormatterStorage<datetime>.Read(reader);
        var __instants = IonFormatterStorage<datetime>.ReadArray(reader);
        var __amounts = IonFormatterStorage<decimal>.ReadArray(reader);
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.EchoMany(__openedat, __instants, __amounts);
        
        IonFormatterStorage<datetime>.WriteArray(writer, result);
    }
    /// <summary>
    /// A `Partial&lt;T&gt;` whose target is made of the new primitives, in both positions.
    /// </summary>
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task Patch_Execute(CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        var service = scope.ServiceProvider.GetRequiredService<ILedgerInteraction>();
    
        const int argumentSize = 2;
    
        var arraySize = reader.ReadStartArray() ?? throw new Exception("undefined len array not allowed");
    
        var __openedat = IonFormatterStorage<datetime>.Read(reader);
        var __patch = IonFormatterStorage<IonPartial<LedgerPatch>>.Read(reader);
    
        reader.ReadEndArrayAndSkip(arraySize - argumentSize);
    
        var result = await service.Patch(__openedat, __patch);
        
        IonFormatterStorage<IonPartial<LedgerPatch>>.Write(writer, result);
    }

    
    
    
        public Task RouteExecuteAsync(string methodName, CborReader reader, CborWriter writer, CancellationToken ct = default)
    {
        
        if (methodName.Equals("Echo", StringComparison.InvariantCultureIgnoreCase))
            return Echo_Execute(reader, writer, ct);
        if (methodName.Equals("EchoAmount", StringComparison.InvariantCultureIgnoreCase))
            return EchoAmount_Execute(reader, writer, ct);
        if (methodName.Equals("Roundtrip", StringComparison.InvariantCultureIgnoreCase))
            return Roundtrip_Execute(reader, writer, ct);
        if (methodName.Equals("EchoMaybe", StringComparison.InvariantCultureIgnoreCase))
            return EchoMaybe_Execute(reader, writer, ct);
        if (methodName.Equals("EchoMany", StringComparison.InvariantCultureIgnoreCase))
            return EchoMany_Execute(reader, writer, ct);
        if (methodName.Equals("Patch", StringComparison.InvariantCultureIgnoreCase))
            return Patch_Execute(reader, writer, ct);

        
        throw new InvalidOperationException("no method defined");
    }
    
    private static readonly string[] __allowedStreamingMethods = [
        
    ];
    
    public bool IsAllowInputStream(string methodName) => __allowedStreamingMethods.Contains(methodName);
}

