//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------
#![allow(dead_code, unused_imports, non_camel_case_types)]
//! Backward/forward compatibility probe schemas.
//!
//! Every "v1"/"v2" pair below is the SAME logical message at two schema revisions, spelled
//! with distinct names so that both revisions can be generated into one module and linked
//! into one test binary. The wire shape is what matters: a message is a positional CBOR
//! array, so a field's identity is its declaration order.

use ion_rustcore::formatter::IonFormat;
use ion_rustcore::{Decoder, Encoder, IonError};

// ═══════════════ Types ═══════════════

#[derive(Debug, Clone, PartialEq)]
pub struct AppendedV1 {
    pub a: i32,
    pub b: String,
}


#[derive(Debug, Clone, PartialEq)]
pub struct AppendedV2 {
    pub a: i32,
    pub b: String,
    pub c: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct InsertedV1 {
    pub a: i32,
    pub c: bool,
}


#[derive(Debug, Clone, PartialEq)]
pub struct InsertedV2 {
    pub a: i32,
    pub b: String,
    pub c: bool,
}


#[derive(Debug, Clone, PartialEq)]
pub struct RemovedV1 {
    pub a: i32,
    pub b: String,
    pub c: bool,
}


#[derive(Debug, Clone, PartialEq)]
pub struct RemovedV2 {
    pub a: i32,
    pub c: bool,
}


#[derive(Debug, Clone, PartialEq)]
pub struct ReorderedV1 {
    pub a: i32,
    pub b: String,
}


#[derive(Debug, Clone, PartialEq)]
pub struct ReorderedV2 {
    pub b: String,
    pub a: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct RetypedV1 {
    pub a: i32,
    pub b: String,
}


#[derive(Debug, Clone, PartialEq)]
pub struct RetypedV2 {
    pub a: i32,
    pub b: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct WidenedV1 {
    pub a: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct WidenedV2 {
    pub a: i64,
}


#[derive(Debug, Clone, PartialEq)]
pub struct OptAddedV1 {
    pub a: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct OptAddedV2 {
    pub a: i32,
    pub b: Option<String>,
}


#[derive(Debug, Clone, PartialEq)]
pub struct OptTightenedV1 {
    pub a: i32,
    pub b: Option<String>,
}


#[derive(Debug, Clone, PartialEq)]
pub struct OptTightenedV2 {
    pub a: i32,
    pub b: String,
}


#[derive(Debug, Clone, PartialEq)]
pub struct VarToFixedV1 {
    pub xs: Vec<i32>,
}


#[derive(Debug, Clone, PartialEq)]
pub struct VarToFixedV2 {
    pub xs: [i32; 3],
}


#[derive(Debug, Clone, PartialEq)]
pub struct EnumHolderV1 {
    pub t: TierV1,
    pub n: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct EnumHolderV2 {
    pub t: TierV2,
    pub n: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct UnionHolderV1 {
    pub s: ShapeV1,
    pub n: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct UnionHolderV2 {
    pub s: ShapeV2,
    pub n: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct NestV1 {
    pub bare: AppendedV1,
    pub list: Vec<AppendedV1>,
    pub slots: [AppendedV1; 2],
    pub by_name: std::collections::HashMap<String, AppendedV1>,
    pub opt: Option<AppendedV1>,
    pub tier: TierV1,
    pub tiers: std::collections::HashSet<TierV1>,
    pub shape: ShapeV1,
    pub tail: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct NestV2 {
    pub bare: AppendedV2,
    pub list: Vec<AppendedV2>,
    pub slots: [AppendedV2; 2],
    pub by_name: std::collections::HashMap<String, AppendedV2>,
    pub opt: Option<AppendedV2>,
    pub tier: TierV2,
    pub tiers: std::collections::HashSet<TierV2>,
    pub shape: ShapeV2,
    pub tail: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct ShiftedV1 {
    pub a: i32,
    pub c: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct ShiftedV2 {
    pub a: i32,
    pub b: i32,
    pub c: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct SwapV1 {
    pub x: i32,
    pub y: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct SwapV2 {
    pub y: i32,
    pub x: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct GrowHolderV1 {
    pub g: GrowV1,
    pub n: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct GrowHolderV2 {
    pub g: GrowV2,
    pub n: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct SetHolderV1 {
    pub s: std::collections::HashSet<TierV1>,
    pub n: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct SetHolderV2 {
    pub s: std::collections::HashSet<TierV2>,
    pub n: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct TreeV1 {
    pub v: i32,
    pub kids: Vec<TreeV1>,
}


ion_rustcore::ion_open_enum! {
    pub enum TierV1: u8 {
        Free = 0,
        Paid = 1,
    }
}


ion_rustcore::ion_open_enum! {
    pub enum TierV2: u8 {
        Free = 0,
        Paid = 1,
        Trial = 2,
    }
}


#[derive(Debug, Clone, PartialEq)]
pub enum ShapeV1 {
    CircleV1(CircleV1),
    SquareV1(SquareV1),
}

impl ShapeV1 {
    pub fn union_index(&self) -> u32 {
        match self {
            Self::CircleV1(_) => 0,
            Self::SquareV1(_) => 1,
        }
    }
}


#[derive(Debug, Clone, PartialEq)]
pub struct CircleV1 {
    pub r: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct SquareV1 {
    pub s: i32,
}


impl IonFormat for ShapeV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (union_index, _depth) =
            ion_rustcore::formatter::read_union_envelope(d, "ShapeV1")?;
        let value = match union_index {
                        0 => ShapeV1::CircleV1(<CircleV1 as IonFormat>::ion_read(d)?),            1 => ShapeV1::SquareV1(<SquareV1 as IonFormat>::ion_read(d)?),
            _ => return Err(IonError::InvalidUnionIndex(union_index)),
        };
        Ok(value)
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        ion_rustcore::formatter::write_union_envelope(e, self.union_index())?;
        match self {
                        Self::CircleV1(v) => v.ion_write(e)?,            Self::SquareV1(v) => v.ion_write(e)?,
        }
        Ok(())
    }
}

impl IonFormat for CircleV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "CircleV1")?;
        let r = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 1)?;
        Ok(Self { r })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(1)?;
        self.r.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for SquareV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "SquareV1")?;
        let s = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 1)?;
        Ok(Self { s })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(1)?;
        self.s.ion_write(e)?;
        Ok(())
    }
}


#[derive(Debug, Clone, PartialEq)]
pub enum ShapeV2 {
    CircleV2(CircleV2),
    SquareV2(SquareV2),
    TriangleV2(TriangleV2),
}

impl ShapeV2 {
    pub fn union_index(&self) -> u32 {
        match self {
            Self::CircleV2(_) => 0,
            Self::SquareV2(_) => 1,
            Self::TriangleV2(_) => 2,
        }
    }
}


#[derive(Debug, Clone, PartialEq)]
pub struct CircleV2 {
    pub r: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct SquareV2 {
    pub s: i32,
}


#[derive(Debug, Clone, PartialEq)]
pub struct TriangleV2 {
    pub t: i32,
}


impl IonFormat for ShapeV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (union_index, _depth) =
            ion_rustcore::formatter::read_union_envelope(d, "ShapeV2")?;
        let value = match union_index {
                        0 => ShapeV2::CircleV2(<CircleV2 as IonFormat>::ion_read(d)?),            1 => ShapeV2::SquareV2(<SquareV2 as IonFormat>::ion_read(d)?),            2 => ShapeV2::TriangleV2(<TriangleV2 as IonFormat>::ion_read(d)?),
            _ => return Err(IonError::InvalidUnionIndex(union_index)),
        };
        Ok(value)
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        ion_rustcore::formatter::write_union_envelope(e, self.union_index())?;
        match self {
                        Self::CircleV2(v) => v.ion_write(e)?,            Self::SquareV2(v) => v.ion_write(e)?,            Self::TriangleV2(v) => v.ion_write(e)?,
        }
        Ok(())
    }
}

impl IonFormat for CircleV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "CircleV2")?;
        let r = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 1)?;
        Ok(Self { r })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(1)?;
        self.r.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for SquareV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "SquareV2")?;
        let s = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 1)?;
        Ok(Self { s })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(1)?;
        self.s.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for TriangleV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "TriangleV2")?;
        let t = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 1)?;
        Ok(Self { t })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(1)?;
        self.t.ion_write(e)?;
        Ok(())
    }
}


#[derive(Debug, Clone, PartialEq)]
pub enum GrowV1 {
    GrowCaseV1(GrowCaseV1),
}

impl GrowV1 {
    pub fn union_index(&self) -> u32 {
        match self {
            Self::GrowCaseV1(_) => 0,
        }
    }
}


#[derive(Debug, Clone, PartialEq)]
pub struct GrowCaseV1 {
    pub a: i32,
    pub b: String,
}


impl IonFormat for GrowV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (union_index, _depth) =
            ion_rustcore::formatter::read_union_envelope(d, "GrowV1")?;
        let value = match union_index {
                        0 => GrowV1::GrowCaseV1(<GrowCaseV1 as IonFormat>::ion_read(d)?),
            _ => return Err(IonError::InvalidUnionIndex(union_index)),
        };
        Ok(value)
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        ion_rustcore::formatter::write_union_envelope(e, self.union_index())?;
        match self {
                        Self::GrowCaseV1(v) => v.ion_write(e)?,
        }
        Ok(())
    }
}

impl IonFormat for GrowCaseV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "GrowCaseV1")?;
        let a = <i32 as IonFormat>::ion_read(d)?;
        let b = <String as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { a, b })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.a.ion_write(e)?;
        self.b.ion_write(e)?;
        Ok(())
    }
}


#[derive(Debug, Clone, PartialEq)]
pub enum GrowV2 {
    GrowCaseV2(GrowCaseV2),
}

impl GrowV2 {
    pub fn union_index(&self) -> u32 {
        match self {
            Self::GrowCaseV2(_) => 0,
        }
    }
}


#[derive(Debug, Clone, PartialEq)]
pub struct GrowCaseV2 {
    pub a: i32,
    pub b: String,
    pub c: i32,
}


impl IonFormat for GrowV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (union_index, _depth) =
            ion_rustcore::formatter::read_union_envelope(d, "GrowV2")?;
        let value = match union_index {
                        0 => GrowV2::GrowCaseV2(<GrowCaseV2 as IonFormat>::ion_read(d)?),
            _ => return Err(IonError::InvalidUnionIndex(union_index)),
        };
        Ok(value)
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        ion_rustcore::formatter::write_union_envelope(e, self.union_index())?;
        match self {
                        Self::GrowCaseV2(v) => v.ion_write(e)?,
        }
        Ok(())
    }
}

impl IonFormat for GrowCaseV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "GrowCaseV2")?;
        let a = <i32 as IonFormat>::ion_read(d)?;
        let b = <String as IonFormat>::ion_read(d)?;
        let c = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 3)?;
        Ok(Self { a, b, c })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(3)?;
        self.a.ion_write(e)?;
        self.b.ion_write(e)?;
        self.c.ion_write(e)?;
        Ok(())
    }
}



// ═══════════════ Formatters ═══════════════

impl IonFormat for AppendedV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "AppendedV1")?;
        let a = <i32 as IonFormat>::ion_read(d)?;
        let b = <String as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { a, b })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.a.ion_write(e)?;
        self.b.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for AppendedV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "AppendedV2")?;
        let a = <i32 as IonFormat>::ion_read(d)?;
        let b = <String as IonFormat>::ion_read(d)?;
        let c = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 3)?;
        Ok(Self { a, b, c })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(3)?;
        self.a.ion_write(e)?;
        self.b.ion_write(e)?;
        self.c.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for InsertedV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "InsertedV1")?;
        let a = <i32 as IonFormat>::ion_read(d)?;
        let c = <bool as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { a, c })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.a.ion_write(e)?;
        self.c.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for InsertedV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "InsertedV2")?;
        let a = <i32 as IonFormat>::ion_read(d)?;
        let b = <String as IonFormat>::ion_read(d)?;
        let c = <bool as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 3)?;
        Ok(Self { a, b, c })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(3)?;
        self.a.ion_write(e)?;
        self.b.ion_write(e)?;
        self.c.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for RemovedV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "RemovedV1")?;
        let a = <i32 as IonFormat>::ion_read(d)?;
        let b = <String as IonFormat>::ion_read(d)?;
        let c = <bool as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 3)?;
        Ok(Self { a, b, c })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(3)?;
        self.a.ion_write(e)?;
        self.b.ion_write(e)?;
        self.c.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for RemovedV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "RemovedV2")?;
        let a = <i32 as IonFormat>::ion_read(d)?;
        let c = <bool as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { a, c })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.a.ion_write(e)?;
        self.c.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for ReorderedV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "ReorderedV1")?;
        let a = <i32 as IonFormat>::ion_read(d)?;
        let b = <String as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { a, b })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.a.ion_write(e)?;
        self.b.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for ReorderedV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "ReorderedV2")?;
        let b = <String as IonFormat>::ion_read(d)?;
        let a = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { b, a })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.b.ion_write(e)?;
        self.a.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for RetypedV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "RetypedV1")?;
        let a = <i32 as IonFormat>::ion_read(d)?;
        let b = <String as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { a, b })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.a.ion_write(e)?;
        self.b.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for RetypedV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "RetypedV2")?;
        let a = <i32 as IonFormat>::ion_read(d)?;
        let b = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { a, b })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.a.ion_write(e)?;
        self.b.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for WidenedV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "WidenedV1")?;
        let a = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 1)?;
        Ok(Self { a })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(1)?;
        self.a.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for WidenedV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "WidenedV2")?;
        let a = <i64 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 1)?;
        Ok(Self { a })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(1)?;
        self.a.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for OptAddedV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "OptAddedV1")?;
        let a = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 1)?;
        Ok(Self { a })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(1)?;
        self.a.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for OptAddedV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "OptAddedV2")?;
        let a = <i32 as IonFormat>::ion_read(d)?;
        let b = ion_rustcore::formatter::read_maybe::<String>(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { a, b })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.a.ion_write(e)?;
        ion_rustcore::formatter::write_maybe(e, &self.b)?;
        Ok(())
    }
}

impl IonFormat for OptTightenedV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "OptTightenedV1")?;
        let a = <i32 as IonFormat>::ion_read(d)?;
        let b = ion_rustcore::formatter::read_maybe::<String>(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { a, b })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.a.ion_write(e)?;
        ion_rustcore::formatter::write_maybe(e, &self.b)?;
        Ok(())
    }
}

impl IonFormat for OptTightenedV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "OptTightenedV2")?;
        let a = <i32 as IonFormat>::ion_read(d)?;
        let b = <String as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { a, b })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.a.ion_write(e)?;
        self.b.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for VarToFixedV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "VarToFixedV1")?;
        let xs = ion_rustcore::formatter::read_array::<i32>(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 1)?;
        Ok(Self { xs })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(1)?;
        ion_rustcore::formatter::write_array(e, &self.xs)?;
        Ok(())
    }
}

impl IonFormat for VarToFixedV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "VarToFixedV2")?;
        let xs = <[i32; 3] as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 1)?;
        Ok(Self { xs })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(1)?;
        self.xs.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for EnumHolderV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "EnumHolderV1")?;
        let t = <TierV1 as IonFormat>::ion_read(d)?;
        let n = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { t, n })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.t.ion_write(e)?;
        self.n.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for EnumHolderV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "EnumHolderV2")?;
        let t = <TierV2 as IonFormat>::ion_read(d)?;
        let n = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { t, n })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.t.ion_write(e)?;
        self.n.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for UnionHolderV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "UnionHolderV1")?;
        let s = <ShapeV1 as IonFormat>::ion_read(d)?;
        let n = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { s, n })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.s.ion_write(e)?;
        self.n.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for UnionHolderV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "UnionHolderV2")?;
        let s = <ShapeV2 as IonFormat>::ion_read(d)?;
        let n = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { s, n })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.s.ion_write(e)?;
        self.n.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for NestV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "NestV1")?;
        let bare = <AppendedV1 as IonFormat>::ion_read(d)?;
        let list = ion_rustcore::formatter::read_array::<AppendedV1>(d)?;
        let slots = <[AppendedV1; 2] as IonFormat>::ion_read(d)?;
        let by_name = <std::collections::HashMap<String, AppendedV1> as IonFormat>::ion_read(d)?;
        let opt = ion_rustcore::formatter::read_maybe::<AppendedV1>(d)?;
        let tier = <TierV1 as IonFormat>::ion_read(d)?;
        let tiers = <std::collections::HashSet<TierV1> as IonFormat>::ion_read(d)?;
        let shape = <ShapeV1 as IonFormat>::ion_read(d)?;
        let tail = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 9)?;
        Ok(Self { bare, list, slots, by_name, opt, tier, tiers, shape, tail })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(9)?;
        self.bare.ion_write(e)?;
        ion_rustcore::formatter::write_array(e, &self.list)?;
        self.slots.ion_write(e)?;
        self.by_name.ion_write(e)?;
        ion_rustcore::formatter::write_maybe(e, &self.opt)?;
        self.tier.ion_write(e)?;
        self.tiers.ion_write(e)?;
        self.shape.ion_write(e)?;
        self.tail.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for NestV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "NestV2")?;
        let bare = <AppendedV2 as IonFormat>::ion_read(d)?;
        let list = ion_rustcore::formatter::read_array::<AppendedV2>(d)?;
        let slots = <[AppendedV2; 2] as IonFormat>::ion_read(d)?;
        let by_name = <std::collections::HashMap<String, AppendedV2> as IonFormat>::ion_read(d)?;
        let opt = ion_rustcore::formatter::read_maybe::<AppendedV2>(d)?;
        let tier = <TierV2 as IonFormat>::ion_read(d)?;
        let tiers = <std::collections::HashSet<TierV2> as IonFormat>::ion_read(d)?;
        let shape = <ShapeV2 as IonFormat>::ion_read(d)?;
        let tail = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 9)?;
        Ok(Self { bare, list, slots, by_name, opt, tier, tiers, shape, tail })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(9)?;
        self.bare.ion_write(e)?;
        ion_rustcore::formatter::write_array(e, &self.list)?;
        self.slots.ion_write(e)?;
        self.by_name.ion_write(e)?;
        ion_rustcore::formatter::write_maybe(e, &self.opt)?;
        self.tier.ion_write(e)?;
        self.tiers.ion_write(e)?;
        self.shape.ion_write(e)?;
        self.tail.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for ShiftedV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "ShiftedV1")?;
        let a = <i32 as IonFormat>::ion_read(d)?;
        let c = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { a, c })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.a.ion_write(e)?;
        self.c.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for ShiftedV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "ShiftedV2")?;
        let a = <i32 as IonFormat>::ion_read(d)?;
        let b = <i32 as IonFormat>::ion_read(d)?;
        let c = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 3)?;
        Ok(Self { a, b, c })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(3)?;
        self.a.ion_write(e)?;
        self.b.ion_write(e)?;
        self.c.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for SwapV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "SwapV1")?;
        let x = <i32 as IonFormat>::ion_read(d)?;
        let y = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { x, y })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.x.ion_write(e)?;
        self.y.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for SwapV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "SwapV2")?;
        let y = <i32 as IonFormat>::ion_read(d)?;
        let x = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { y, x })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.y.ion_write(e)?;
        self.x.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for GrowHolderV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "GrowHolderV1")?;
        let g = <GrowV1 as IonFormat>::ion_read(d)?;
        let n = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { g, n })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.g.ion_write(e)?;
        self.n.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for GrowHolderV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "GrowHolderV2")?;
        let g = <GrowV2 as IonFormat>::ion_read(d)?;
        let n = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { g, n })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.g.ion_write(e)?;
        self.n.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for SetHolderV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "SetHolderV1")?;
        let s = <std::collections::HashSet<TierV1> as IonFormat>::ion_read(d)?;
        let n = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { s, n })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.s.ion_write(e)?;
        self.n.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for SetHolderV2 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "SetHolderV2")?;
        let s = <std::collections::HashSet<TierV2> as IonFormat>::ion_read(d)?;
        let n = <i32 as IonFormat>::ion_read(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { s, n })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.s.ion_write(e)?;
        self.n.ion_write(e)?;
        Ok(())
    }
}

impl IonFormat for TreeV1 {
    fn ion_read(d: &mut Decoder<'_>) -> Result<Self, IonError> {
        let (len, _depth) = ion_rustcore::formatter::read_message_header(d, "TreeV1")?;
        let v = <i32 as IonFormat>::ion_read(d)?;
        let kids = ion_rustcore::formatter::read_array::<TreeV1>(d)?;
        ion_rustcore::formatter::skip_remaining(d, len, 2)?;
        Ok(Self { v, kids })
    }

    fn ion_write(&self, e: &mut Encoder<Vec<u8>>) -> Result<(), IonError> {
        e.array(2)?;
        self.v.ion_write(e)?;
        ion_rustcore::formatter::write_array(e, &self.kids)?;
        Ok(())
    }
}


// ═══════════════ Service Clients ═══════════════

pub struct CompatSvcV1Client {
    ctx: ion_rustcore::IonClientContext,
}

impl ion_rustcore::FromContext for CompatSvcV1Client {
    fn from_context(ctx: ion_rustcore::IonClientContext) -> Self {
        Self { ctx }
    }
}

impl CompatSvcV1Client {
        pub async fn echo(&self, v: &AppendedV1) -> Result<AppendedV1, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(1)?;
        v.ion_write(&mut e)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "ICompatSvcV1", "Echo");
        req.call::<AppendedV1>(&buf).await
    }
    pub async fn echo_nest(&self, v: &NestV1, tail: i32) -> Result<NestV1, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(2)?;
        v.ion_write(&mut e)?;
        tail.ion_write(&mut e)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "ICompatSvcV1", "EchoNest");
        req.call::<NestV1>(&buf).await
    }

}

pub struct CompatSvcV2Client {
    ctx: ion_rustcore::IonClientContext,
}

impl ion_rustcore::FromContext for CompatSvcV2Client {
    fn from_context(ctx: ion_rustcore::IonClientContext) -> Self {
        Self { ctx }
    }
}

impl CompatSvcV2Client {
        pub async fn echo(&self, v: &AppendedV2) -> Result<AppendedV2, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(1)?;
        v.ion_write(&mut e)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "ICompatSvcV2", "Echo");
        req.call::<AppendedV2>(&buf).await
    }
    pub async fn echo_nest(&self, v: &NestV2, tail: i32) -> Result<NestV2, ion_rustcore::IonError> {
        let mut e = ion_rustcore::Encoder::new(Vec::new());
        e.array(2)?;
        v.ion_write(&mut e)?;
        tail.ion_write(&mut e)?;
        let buf = e.into_writer();
        let req = ion_rustcore::IonRequest::new(&self.ctx, "ICompatSvcV2", "EchoNest");
        req.call::<NestV2>(&buf).await
    }

}


