//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace TestContracts;

/// <summary>
/// Keyword names in method and argument position.
/// </summary>
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_KeywordInteraction_ClientImpl(IonClientContext context) : IKeywordInteraction
{
    
    private static readonly Lazy<MethodInfo> Echo_Ref = new(() =>
        typeof(IKeywordInteraction).GetMethod(nameof(Echo), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> lock_Ref = new(() =>
        typeof(IKeywordInteraction).GetMethod(nameof(@lock), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> Roundtrip_Ref = new(() =>
        typeof(IKeywordInteraction).GetMethod(nameof(Roundtrip), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> Patch_Ref = new(() =>
        typeof(IKeywordInteraction).GetMethod(nameof(Patch), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> Pick_Ref = new(() =>
        typeof(IKeywordInteraction).GetMethod(nameof(Pick), BindingFlags.Public | BindingFlags.Instance)!);


    
    /// <summary>
    /// Reserved words as method *parameters*: a C# parameter, a Rust `async fn` argument
    /// and — the one that actually fails without a rename — a TypeScript parameter.
    /// </summary>
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<string> Echo(string __class, i4 __type, bool __default, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IKeywordInteraction), Echo_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 3;
    
        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<string>.Write(writer, __class);
        IonFormatterStorage<i4>.Write(writer, __type);
        IonFormatterStorage<bool>.Write(writer, __default);
        
        writer.WriteEndArray();
    
        return await req.CallAsync<string>(writer.Encode(), ct: ct);
    }
    /// <summary>
    /// A reserved word as the *method* name. The router still dispatches on the Ion
    /// spelling: the generated `methodName.Equals("lock", …)` is a string, not an
    /// identifier, and `nameof(@lock)` is `"lock"`.
    /// </summary>
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<i4> @lock(i4 __value, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IKeywordInteraction), lock_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 1;
    
        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<i4>.Write(writer, __value);
        
        writer.WriteEndArray();
    
        return await req.CallAsync<i4>(writer.Encode(), ct: ct);
    }
    /// <summary>
    /// The whole message over a real signature.
    /// </summary>
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<KeywordFields> Roundtrip(KeywordFields __fields, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IKeywordInteraction), Roundtrip_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 1;
    
        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<KeywordFields>.Write(writer, __fields);
        
        writer.WriteEndArray();
    
        return await req.CallAsync<KeywordFields>(writer.Encode(), ct: ct);
    }
    /// <summary>
    /// A patch in argument and return position, so the field-name keys are exercised
    /// end to end.
    /// </summary>
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<IonPartial<KeywordPatchTarget>> Patch(IonPartial<KeywordPatchTarget> __patch, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IKeywordInteraction), Patch_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 1;
    
        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<IonPartial<KeywordPatchTarget>>.Write(writer, __patch);
        
        writer.WriteEndArray();
    
        return await req.CallAsync<IonPartial<KeywordPatchTarget>>(writer.Encode(), ct: ct);
    }
    /// <summary>
    /// The union in both positions.
    /// </summary>
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<IKeywordUnion> Pick(IKeywordUnion __choice, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(IKeywordInteraction), Pick_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 1;
    
        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<IKeywordUnion>.Write(writer, __choice);
        
        writer.WriteEndArray();
    
        return await req.CallAsync<IKeywordUnion>(writer.Encode(), ct: ct);
    }

}

