//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace TestContracts;

/// <summary>
/// Round-trip surface for `datetime` and `decimal`.
///
/// The service level operand is itself a `datetime`, so every generated method signature
/// carries one — that is the position that would have gone unnoticed if only fields were
/// covered.
/// </summary>
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_LedgerInteraction_ClientImpl(IonClientContext context) : ILedgerInteraction
{
    
    private static readonly Lazy<MethodInfo> Echo_Ref = new(() =>
        typeof(ILedgerInteraction).GetMethod(nameof(Echo), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> EchoAmount_Ref = new(() =>
        typeof(ILedgerInteraction).GetMethod(nameof(EchoAmount), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> Roundtrip_Ref = new(() =>
        typeof(ILedgerInteraction).GetMethod(nameof(Roundtrip), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> EchoMaybe_Ref = new(() =>
        typeof(ILedgerInteraction).GetMethod(nameof(EchoMaybe), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> EchoMany_Ref = new(() =>
        typeof(ILedgerInteraction).GetMethod(nameof(EchoMany), BindingFlags.Public | BindingFlags.Instance)!);
    private static readonly Lazy<MethodInfo> Patch_Ref = new(() =>
        typeof(ILedgerInteraction).GetMethod(nameof(Patch), BindingFlags.Public | BindingFlags.Instance)!);


    
    /// <summary>
    /// `datetime` in both argument and return position. The one method whose result proves
    /// the offset and the sub-millisecond tick survived the wire.
    /// </summary>
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<datetime> Echo(datetime __openedat, datetime __at, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(ILedgerInteraction), Echo_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 2;
    
        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<datetime>.Write(writer, __openedat);
        IonFormatterStorage<datetime>.Write(writer, __at);
        
        writer.WriteEndArray();
    
        return await req.CallAsync<datetime>(writer.Encode(), ct: ct);
    }
    /// <summary>
    /// `decimal` in both argument and return position.
    /// </summary>
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<decimal> EchoAmount(datetime __openedat, decimal __amount, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(ILedgerInteraction), EchoAmount_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 2;
    
        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<datetime>.Write(writer, __openedat);
        IonFormatterStorage<decimal>.Write(writer, __amount);
        
        writer.WriteEndArray();
    
        return await req.CallAsync<decimal>(writer.Encode(), ct: ct);
    }
    /// <summary>
    /// The whole message, so every field shape above goes over a real transport.
    /// </summary>
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<LedgerEntry> Roundtrip(datetime __openedat, LedgerEntry __entry, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(ILedgerInteraction), Roundtrip_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 2;
    
        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<datetime>.Write(writer, __openedat);
        IonFormatterStorage<LedgerEntry>.Write(writer, __entry);
        
        writer.WriteEndArray();
    
        return await req.CallAsync<LedgerEntry>(writer.Encode(), ct: ct);
    }
    /// <summary>
    /// Optional in argument and return position: `Maybe&lt;datetime&gt;` / `Maybe&lt;decimal&gt;`.
    /// A null `amount` returns null, so the null branch is reachable.
    /// </summary>
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<decimal?> EchoMaybe(datetime __openedat, datetime? __at, decimal? __amount, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(ILedgerInteraction), EchoMaybe_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 3;
    
        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<datetime>.Write(writer, __openedat);
        IonFormatterStorage<datetime>.WriteNullable(writer, __at);
        IonFormatterStorage<decimal>.WriteNullable(writer, __amount);
        
        writer.WriteEndArray();
    
        return await req.CallAsyncNullable<decimal>(writer.Encode(), ct: ct);
    }
    /// <summary>
    /// Arrays of both, with an array return.
    /// </summary>
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<IonArray<datetime>> EchoMany(datetime __openedat, IonArray<datetime> __instants, IonArray<decimal> __amounts, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(ILedgerInteraction), EchoMany_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 3;
    
        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<datetime>.Write(writer, __openedat);
        IonFormatterStorage<datetime>.WriteArray(writer, __instants);
        IonFormatterStorage<decimal>.WriteArray(writer, __amounts);
        
        writer.WriteEndArray();
    
        return await req.CallAsyncWithArray<datetime>(writer.Encode(), ct: ct);
    }
    /// <summary>
    /// A `Partial&lt;T&gt;` whose target is made of the new primitives, in both positions.
    /// </summary>
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public async Task<IonPartial<LedgerPatch>> Patch(datetime __openedat, IonPartial<LedgerPatch> __patch, CancellationToken ct = default)
    {
        var req = new IonRequest(context, typeof(ILedgerInteraction), Patch_Ref.Value);
    
        var writer = new CborWriter();
        
        const int argsSize = 2;
    
        writer.WriteStartArray(argsSize);
        
        IonFormatterStorage<datetime>.Write(writer, __openedat);
        IonFormatterStorage<IonPartial<LedgerPatch>>.Write(writer, __patch);
        
        writer.WriteEndArray();
    
        return await req.CallAsync<IonPartial<LedgerPatch>>(writer.Encode(), ct: ct);
    }

}

