//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a code generation tool.
//     Changes to this file may cause incorrect behavior and will be lost
//     if the code is regenerated.
//
//     Generator: IonPath Codegen
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable
#nullable enable


namespace ion.runtime.locking;
[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_LockFileEntity_Formatter : IonFormatter<LockFileEntity>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public LockFileEntity Read(CborReader reader)
    {
        var __lockformat = IonFormatterStorage<i4>.Read(reader);
        var __schemaid = IonFormatterStorage<string>.Read(reader);
        var __toolversion = IonFormatterStorage<string>.Read(reader);
        var __bodysha256 = IonFormatterStorage<u1>.ReadArray(reader);
        var __types = IonFormatterStorage<TypeEntity>.ReadArray(reader);
        return new(__lockformat, __schemaid, __toolversion, __bodysha256, __types);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, LockFileEntity value)
    {
        IonFormatterStorage<i4>.Write(writer, value.lockFormat);
        IonFormatterStorage<string>.Write(writer, value.schemaId);
        IonFormatterStorage<string>.Write(writer, value.toolVersion);
        IonFormatterStorage<u1>.WriteArray(writer, value.bodySha256);
        IonFormatterStorage<TypeEntity>.WriteArray(writer, value.types);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_TypeEntity_Formatter : IonFormatter<TypeEntity>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public TypeEntity Read(CborReader reader)
    {
        var __name = IonFormatterStorage<string>.Read(reader);
        var __fields = IonFormatterStorage<FieldEntity>.ReadArray(reader);
        var __attrs = IonFormatterStorage<AttributeEntity>.ReadArray(reader);
        return new(__name, __fields, __attrs);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, TypeEntity value)
    {
        IonFormatterStorage<string>.Write(writer, value.name);
        IonFormatterStorage<FieldEntity>.WriteArray(writer, value.fields);
        IonFormatterStorage<AttributeEntity>.WriteArray(writer, value.attrs);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_FieldEntity_Formatter : IonFormatter<FieldEntity>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public FieldEntity Read(CborReader reader)
    {
        var __name = IonFormatterStorage<string>.Read(reader);
        var __type = IonFormatterStorage<string>.Read(reader);
        var __isoptional = IonFormatterStorage<bool>.Read(reader);
        var __pos = IonFormatterStorage<i4>.Read(reader);
        var __attrs = IonFormatterStorage<AttributeEntity>.ReadArray(reader);
        return new(__name, __type, __isoptional, __pos, __attrs);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, FieldEntity value)
    {
        IonFormatterStorage<string>.Write(writer, value.name);
        IonFormatterStorage<string>.Write(writer, value.type);
        IonFormatterStorage<bool>.Write(writer, value.isOptional);
        IonFormatterStorage<i4>.Write(writer, value.pos);
        IonFormatterStorage<AttributeEntity>.WriteArray(writer, value.attrs);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_MethodEntity_Formatter : IonFormatter<MethodEntity>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public MethodEntity Read(CborReader reader)
    {
        var __name = IonFormatterStorage<string>.Read(reader);
        var __returntype = IonFormatterStorage<string>.Read(reader);
        var __pos = IonFormatterStorage<i4>.Read(reader);
        var __args = IonFormatterStorage<ArgumentEntity>.ReadArray(reader);
        var __attrs = IonFormatterStorage<AttributeEntity>.ReadArray(reader);
        return new(__name, __returntype, __pos, __args, __attrs);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, MethodEntity value)
    {
        IonFormatterStorage<string>.Write(writer, value.name);
        IonFormatterStorage<string>.Write(writer, value.returnType);
        IonFormatterStorage<i4>.Write(writer, value.pos);
        IonFormatterStorage<ArgumentEntity>.WriteArray(writer, value.args);
        IonFormatterStorage<AttributeEntity>.WriteArray(writer, value.attrs);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_ArgumentEntity_Formatter : IonFormatter<ArgumentEntity>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public ArgumentEntity Read(CborReader reader)
    {
        var __name = IonFormatterStorage<string>.Read(reader);
        var __type = IonFormatterStorage<string>.Read(reader);
        var __attrs = IonFormatterStorage<AttributeEntity>.ReadArray(reader);
        return new(__name, __type, __attrs);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, ArgumentEntity value)
    {
        IonFormatterStorage<string>.Write(writer, value.name);
        IonFormatterStorage<string>.Write(writer, value.type);
        IonFormatterStorage<AttributeEntity>.WriteArray(writer, value.attrs);
    }
}

[GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
public sealed class Ion_AttributeEntity_Formatter : IonFormatter<AttributeEntity>
{
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public AttributeEntity Read(CborReader reader)
    {
        var __name = IonFormatterStorage<string>.Read(reader);
        var __args = IonFormatterStorage<string>.ReadArray(reader);
        return new(__name, __args);
    }
    
    [GeneratedCodeAttribute("ionc", null), CompilerGeneratedAttribute]
    public void Write(CborWriter writer, AttributeEntity value)
    {
        IonFormatterStorage<string>.Write(writer, value.name);
        IonFormatterStorage<string>.WriteArray(writer, value.args);
    }
}

